### ISSUE TITLE
Onboarding: crop site icon image after selection

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#1000]
Suggested [here](https://github.com/Automattic/newspack-plugin/pull/863#pullrequestreview-590551296):

> since we are requesting a square, it'd be nice to have a "Crop image" screen just like in the customizer.

The way it works in the Customizer is by [initialising `wp.media` with `states`](https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-admin/js/customize-controls.js#L4716-L4730). I haven't been able to reproduce that outside of the Customizer, though. 
Gutenberg editor, though, [uses](https://github.com/WordPress/gutenberg/blob/3da717b8d0/packages/block-library/src/image/image-editing/cropper.js) a library called [`react-easy-crop`](https://www.npmjs.com/package/react-easy-crop), this might be a better shot - this would need a UI, though.

**Comment by thomasguillot** [comment]
Seems overkill for now. The Site Icon can live without it 😊
