### ISSUE TITLE
Fatal Error when setting up Reader Revenue on a new site

### ISSUE THREAD

**Issue by thekaitlin** [Automattic/newspack-plugin#1011]
**Describe the bug**
During setup for Reader Revenue, after selecting `Newspack`, a fatal error occurred, preventing any further steps from being taken or being able to edit anything in the Newspack wizard.

<img width="500" alt="Screen Shot 2021-06-16 at 2 27 19 PM" src="https://user-images.githubusercontent.com/2072208/122482329-8e51dc80-cf8d-11eb-8d79-5c4b07954e4c.png">

**To Reproduce**
1. Created a new site with Knife
2. Enabled the Newspack debug constant in wp-config.php
3. Went through the onboarding flow for the site -- note that it asked for Stripe credentials, and I realized at that point that I only had a production public key for the publisher, and no secret key, so I proceeded without providing Stripe credentials.
4. Once I completed the initial pass through the onboarding, I clicked on the option for Reader Revenue. Once I selected Newspack from the drop-down, the error shown in the screenshot above popped up.
5. After going back to the Dashboard, every option on the Newspack Dashboard resulted in the same error.
6. Through the browser CLI, @tmmbecker checked the PHP errors and saw the following:

```
PHP Fatal error:  Uncaught Error: Class ‘WC_Payment_Gateways’ not found in /wordpress/plugins/newspack-plugin/1.45.0/includes/configuration_managers/class-woocommerce-configuration-manager.php:104
```

Based on this error, we realized that WooCommerce wasn't yet installed. Once I installed WooCommerce, the error went away.

_Additionally_, once WooCommerce was installed, I was able to set suggested donation amounts, but even after saving, they seemed to disappear. I realized this was because the additional premium plugin extensions (Name Your Price and Subscriptions) weren't installed either. 

**Expected Behavior**

Once choosing Newspack, the required plugin(s) would be installed automatically rather than generating an error message or silently failing to save.

**Comment by claudiulodro** [comment]
#1046 fixed this issue. See https://github.com/Automattic/newspack-plugin/pull/1042#issuecomment-882545950
