### ISSUE TITLE
Component: Toggle

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#102]
We should implement the Muriel-designed toggle, so we're not using the basic WP core toggle everywhere. Like the other Muriel components, this should have the same class name and usage as the core component.

Core toggle:

<img width="182" alt="Screen Shot 2019-06-12 at 11 47 26 AM" src="https://user-images.githubusercontent.com/7317227/59377872-ece18180-8d07-11e9-917d-b490cbba922b.png">
<img width="170" alt="Screen Shot 2019-06-12 at 11 47 34 AM" src="https://user-images.githubusercontent.com/7317227/59377873-ece18180-8d07-11e9-81c6-c30e2a62d0ef.png">

Muriel toggle:

<img width="197" alt="Screen Shot 2019-06-12 at 11 46 21 AM" src="https://user-images.githubusercontent.com/7317227/59377828-d20f0d00-8d07-11e9-9457-770bd5da5be0.png">

**Comment by thomasguillot** [comment]
Out-of-date design
