### ISSUE TITLE
Archive & Search global ads have no frontend handling?

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#1020]
**Describe the bug**

I was looking through the [code for the Ads Wizard, and I didn't notice any handling for when people set a global Archive or a global Search Results ad](https://github.com/Automattic/newspack-plugin/blob/master/includes/wizards/class-advertising-wizard.php#L68-L71). We should either remove those settings or add frontend handling for global Archive and Search Results ads

**To Reproduce**
1. Set an ad as a global Archive or Search Results ad.
2. View on the frontend. Observe no special Archive or Search Results ad is output.

**Expected behavior**
I expect the setting to do something if it's there :)

**Comment by adekbadek** [comment]
Yep, they did not. Removed in #1024
