### ISSUE TITLE
SelectControl components render too tall in WP 5.8

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#1036]
**Describe the bug**
I'm pretty sure this is coming straight from [CSS in Gutenberg](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/flex/flex/hook.js#L76), so I'm not sure where this issue should live. Logging here to start, but if this truly affects everyone's editor we should probably re-file in the Gutenberg repo after implementing a workaround.

In WP 5.8+, the `SelectControl` component renders extremely tall due to a `height: 100%` CSS style. See screenshot below.

Setting the height to `height: auto;` instead fixes the issue. This affects all `SelectControl` instances throughout the WP admin UI so we'll need to override this CSS on every admin page that uses `SelectControl`.

**To Reproduce**

1. On a site running WP 5.8, load a block that uses the `SelectControl` component. Examples: Curated List in query mode (see screenshot), Ad Unit block
2. Observe the height of the component is too tall

**Screenshots**

<img width="750" alt="Screen Shot 2021-07-09 at 2 05 24 PM" src="https://user-images.githubusercontent.com/2230142/125131026-4c651380-e0bf-11eb-94a7-be0ef79a5d4d.png">

**Comment by thomasguillot** [comment]
I noticed this too. But it also happens on Core's blocks. You can see an example if you look at the Styles of a Quote block. 

![Screenshot 2021-07-12 at 16 23 24](https://user-images.githubusercontent.com/177929/125313820-850a2480-e32d-11eb-821a-3010a2fe032f.png)

**Comment by dkoo** [comment]
Ah yes, it's definitely an issue in Core CSS. But it's disruptive enough that I wonder if we should implement a fix on our end until they fix it in Core?

**Comment by thomasguillot** [comment]
I'd be surprised if they don't fix it before launching 5.8 🤔

**Comment by dkoo** [comment]
Ok, let's put this issue on hold for now to make sure they do 😄

**Comment by thomasguillot** [comment]
Looks fixed in WP5.8
