### ISSUE TITLE
Issues in SEO wizard when Yoast isn't active

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#1043]
**Describe the bug**
If you visit the SEO wizard when Yoast isn't active, you get a variety of weird undefined behavior. For example, the webmaster tools verifications always show as `[object Object]`. No message is shown to the user letting them know that Yoast is needed for the SEO wizard.

**To Reproduce**
1. Deactivate Yoast
2. Go to Newspack > SEO > Webmaster tools.
3. Observe values are `[object Object]` and if you inspect the network request you get errors about required plugins not active
4. Activate Yoast. Observe wizard behaves correctly.

**Screenshots**

<img width="1488" alt="Screen Shot 2021-07-15 at 10 09 03 AM" src="https://user-images.githubusercontent.com/7317227/125829359-cd229732-ece2-4cd7-9889-143499fbfd0a.png">

**Expected behavior**
If Yoast isn't active, I expect that screen to appear that installs and activates Yoast when I visit the SEO wizard. It shouldn't be possible to access the setting screens if Yoast isn't active.

**Comment by adekbadek** [comment]
@claudiulodro That's probably also caused by the debug mode being on, could you please check?

**Comment by claudiulodro** [comment]
The issue was that Newspack Debug was on, as it forces Yoast to install and activate otherwise, so the issue doesn't happen. Thanks for the tip!
