### ISSUE TITLE
UX issues with Reader Revenue wizard

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-plugin#1051]
The Reader Revenue NRH form is lacking some UX tweaks:

 - There is no indication as to which fields are required.
 - Not filling the required field outputs no error/warning message:

https://user-images.githubusercontent.com/820752/126177546-2e045cf5-c791-44c8-b97a-8a62dfb394d7.mov

 - Clearing the required field outputs a generic error and does not clear the value (which is not updated to the UI unless we refresh the page):

https://user-images.githubusercontent.com/820752/126177862-86d1171a-7ef6-4a53-9e24-5ae47fa8dff7.mov

**Comment by adekbadek** [comment]
Closed in #1050

**Comment by adekbadek** [comment]
Added a "(required)" note to the label in #1050 - since this part of the wizard is a one-time setup, would this be enough?
