### ISSUE TITLE
Carousel strip

### ISSUE THREAD

**Issue by davidfritze** [Automattic/newspack-plugin#108]
I'm looking for ways to breathe more life into our home page design and elements while remaining cognizant that Oklahoma Watch has a small staff for now and we can't have so many home-page fixtures and stories that we can't refresh them often.

That said, I'd like to request that this feature be added to the home-page design - or, if it;s already doable through Gutenberg (which we are still learning), let me know:

-The ability to add what I call a carousel strip in one or two places on the home page - about midway down as well as toward the bottom. An example can be found at [ajc.com, ](https://www.ajc.com/)which uses a number of - almost too many - carousel strips. These also appear on their mobile site. I'd like only a couple. I also prefers ones with large, noticeable left and right arrows that are inset in the photos. I think the strips promote interactivity. Ads can also be interspersed in the strip.

I'm open to your thoughts on whether these draw users. Carousels used to be popular in the top-story position, but are passe. But I like the image strips because only a photo and headline show, they're small and they're quick.

**Comment by philipjohn** [comment]
The AMP Carousel component should allow us to do this. Some examples, which include the large arrows  you like can be seen here: http://ampexamples.com/amp-carousel-slider-1476.html

What I'm not currently sure of is how easily we can add article headlines/blurbs/bylines to the carousel, but I'm asking around about that.

**Comment by thomasguillot** [comment]
Closing this since Newspack now has its own Carousel block: https://github.com/Automattic/newspack-blocks/tree/master/src/blocks/carousel
