### ISSUE TITLE
Protect pages from being deleted by other plugins

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-plugin#1086]
v1.48.0 added protection for the front page, blog page, privacy policy, and WooCommerce pages, preventing them from being deleted by users. https://github.com/Automattic/newspack-plugin/pull/1030

As @dkoo noted in the standalone plugin version of this feature, it's only users who are prevented from deleting these pages; other plugins can still do so. https://github.com/Automattic/newspack-custom-code/pull/5#pullrequestreview-701176547

To prevent other plugins from deleting pages, we probably need to hook into different filters that happen before a) a post hits the trash, and b) before it gets permanently deleted.

**Comment by gamebits** [comment]
Theoretically, upon plugin deactivation:

```
function deactivate_plugin() {

    $page_id = get_option('vidpage');
    wp_delete_post($page_id);

}
register_deactivation_hook( __FILE__, 'deactivate_plugin' );
```

Or perhaps if WooCommerce got uninstalled then reinstalled:

https://github.com/Automattic/woocommerce/blob/75c341494c318f79695fe8a2247737eb329d67a7/plugins/woocommerce/tests/legacy/unit-tests/util/install.php#L76-L81

**Comment by adekbadek** [comment]
The code in the link is test code. I did not find any side-effect-page-deletion in WooCommerce source code. Let's revisit this is such page deletion happens in the wild.
