### ISSUE TITLE
Handoff banner: Text should be customizable

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-plugin#1089]
Looking at the handoff banner during the onboarding, "Return to Newspack after completing configuration" makes sense. But if I navigate to Newspack > Syndication > RSS Enhancements - Manage, then it doesn't make any sense to have the same text since I'm not configuring anything, I'm managing my RSS feeds.

It'd make sense to allow customisation of the text here so it can be more specific to the screen the user is currently editing.

![example](https://user-images.githubusercontent.com/177929/128716155-8242c650-ff6e-41c8-9ba1-b1f03a051826.gif)

**Comment by adekbadek** [comment]
Hm, I'd argue that editing a plugin's settings could be called _configuring_ it. I don't think the text on the banner has any disruptive potential for the users. I'll close the issue, but feel free to reopen if you don't agree.
