### ISSUE TITLE
 Uncaught Error: Call to a member function all() on null in class-stripe-connection.php

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1116]
**Describe the bug**
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function all() on null in /newspack-plugin/includes/class-stripe-connection.php:120

**To Reproduce**
1. Set define( 'NEWSPACK_AMP_PLUS_ENABLED', true );
2. Go to Reader Revenue Page
3. See error in logs

"PHP message: PHP Fatal error:  Uncaught Error: Call to a member function all() on null in /newspack-plugin/includes/class-stripe-connection.php:120
Stack trace:
0 /newspack-plugin/includes/wizards/class-reader-revenue-wizard.php(636): Newspack\Stripe_Connection::list_webhooks()
1 /newspack-plugin/includes/wizards/class-reader-revenue-wizard.php(293): Newspack\Reader_Revenue_Wizard->fetch_all_data()
2 /wp-includes/rest-api/class-wp-rest-server.php(1140): Newspack\Reader_Revenue_Wizard->api_fetch()
3 /rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request()
4 /wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch()
5 /wp-includes/rest-api.php(370): WP_REST_Server->serve_request()

**Screenshots**
Screenshot of error on Readers Revenue Page

![Screenshot](https://user-images.githubusercontent.com/7325107/131215312-2c6fe90d-ba10-4292-886a-efb4940bb03c.png)

**Expected behavior**
Revenue page should list 3 Platforms without any error. Please note that WooCoomerce and Stripe Gateway plugin are in use earlier and enabled. Error is occurring in both case of WooCoomerce and Stripe Gateway plugin enabled and disabled.

**Comment by yogeshbeniwal** [comment]
@adekbadek Not sure if i bring it to your attention or other repository members. Happy to provide more details if required.

**Comment by adekbadek** [comment]
@yogeshbeniwal Thanks for catching that! Should be fixed in https://github.com/Automattic/newspack-plugin/pull/1128
