### ISSUE TITLE
Add Classic Widgets plugin to required plugins

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#1124]
If using the Classic Widgets plugin is intended to  be used on all sites (or at least available) in the short-term, it would make sense to include it in the Newspack Plugin, and activate it as part of the installation process.

That way, it will be automatically added and activated to all new sites.

**Comment by miguelpeixe** [comment]
The Classic Widgets plugin consists in the following 2 lines:

```
// Disables the block editor from managing widgets in the Gutenberg plugin.
add_filter( 'gutenberg_use_widgets_block_editor', '__return_false' );
// Disables the block editor from managing widgets.
add_filter( 'use_widgets_block_editor', '__return_false' );
```

I think we could add the code instead of requiring the plugin.
