### ISSUE TITLE
Design Wizard: Installing starter content changes header settings

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#1134]
**Describe the bug**
If you run the Newspack wizard and install the starter content _after_ you've made some customizations, some of them are overwritten. Specifically:

1. The header gets a background colour
2. The header switches to the 'short' layout
3. The homepage is replaced (similar to #1099), though the original page is still there, a new page is created and just replaces it in the customizer. 

I'm wondering if _not_ making the 'Starter Content' selected by default could help avoid this accidentally being run. 

**To Reproduce**
1. Start with a test site with the Newspack plugin, theme, and blocks installed.
2. Hop into the Customizer and make some changes; leave the header with the default BG, and default height. 
3. Run the Newspack Wizard, including installing starter content.
4. Don't change any of the design settings; if you look you may notice some of the header settings (aren't what you set (solid BG, short header)
5. View the design settings on the front-end and note the difference.

**Screenshots**
Wizard screenshot:

![Screen Shot 2021-09-09 at 4 53 33 PM](https://user-images.githubusercontent.com/177561/132777251-7f8aa410-55bf-4dac-be8f-47481dceb915.png)

How my site originally looked:
![Screen Shot 2021-09-09 at 4 35 15 PM](https://user-images.githubusercontent.com/177561/132777254-8ee5f5c2-3a9e-4a9a-89a9-50da857701c7.png)

After running the wizard:
![image (4)](https://user-images.githubusercontent.com/177561/132777281-43dab0ca-0f7c-447c-8696-a24477dacb77.png)

**Expected behavior**
All of my settings would be maintained (or at least the header ones; the homepage changing somewhat makes sense!)

**Comment by adekbadek** [comment]
@laurelfulford – both header options are treated as `false` by default in the Theme. WDYT about removing setting them to `true` during setup, to bring setup in line with Theme's defaults?

**Comment by laurelfulford** [comment]
@adekbadek That does seem like it might be the safest bet! 

At the time of filing this I thought there might be an easy-ish way to check if anything had been changed before overwriting it, but you can't exactly check for header changes when none have been made, and checking for other things (like colours or fonts) isn't exactly definitive! 

This has turned into more of an edge case issue for us as we've been getting publishers to run the wizard as the very first step. I'm not sure if there's an argument for keeping the wizard more opinionated for these settings, but if there is I haven't run into this issue on a site in a while!
