### ISSUE TITLE
Analytics: NTG causing AMPAnalytics error

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-plugin#1144]
**Describe the bug**

News Tagging Guide custom events is throwing this error:

> [AmpAnalytics <unknown id>] The tag should contain only one <script> child.

![Screen Shot on 2021-09-15 at 18-02-10](https://user-images.githubusercontent.com/22805865/133515821-91d67251-3d37-4068-834b-71c624b9ba0e.png)

**To Reproduce**
1. Open the Console.
2. Go to https://reporternewspaper-clone.newspackstaging.com/atlantaseniorlife/
2. Note the error.
3. Go to the [Custom Events page](https://reporternewspaper-clone.newspackstaging.com/wp-admin/admin.php?page=newspack-analytics-wizard#/custom-events) and turn off NTG events.
4. Refresh to the ASL page.
5. Note that the error is gone.

**Comment by tmmbecker** [comment]
Upon further testing, this is related to something else in AMP. I didn't realize that I hadn't turned AMP back on :/

**Comment by adekbadek** [comment]
Can't reproduce neither on the mentioned site nor locally. Feel free to reopen if the issues resurfaces.
