### ISSUE TITLE
Site Design Wizard: Tagline populates 'Copyright' field

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#1148]
**Describe the bug**
When you run through the Design Wizard, if the site has a tagline the value ends up saved as the 'Copyright Information'(under Customizer > Footer Settings).

The copyright will display the Site Name by default unless a value is added here; it would probably make the most sense to leave this field blank as part of the design wizard, and leave it to the publisher to edit/override if needed.

**Comment by adekbadek** [comment]
This was added in https://github.com/Automattic/newspack-plugin/pull/892, but there's no discussion there that would support this decision. I've remove this default value setting in https://github.com/Automattic/newspack-plugin/pull/1432
