### ISSUE TITLE
Social sharing: AMP support for Email Share

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-plugin#1169]
This is part of the long-standing [Jetpack issue](https://github.com/Automattic/jetpack/issues/9730) and we’ve previously flagged it [internally](153-gh-Automattic) as well.

**Is your feature request related to a problem? Please describe.**
Publishers would like to have an option for readers to share their posts via email. The Jetpack solution doesn't work because it's not AMP-friendly. So it gets stripped even when it's added. 

**Describe the solution you'd like**
@aschweigert explained that they spent quite a bit of effort on this at Largo and came up with [this](https://github.com/WPBuddy/largo/blob/trunk/inc/post-social.php#L107). 

**Describe alternatives you've considered**
I've been suggesting the Add to Any plugin as a workaround. 

**Additional context**
Let's use this issue to track requests. Email shares are becoming a thing of the past and most publishers have requested it for their more senior readers, who still use email. 

We may find that this is just a temporary surge and with time, people will forget and we don't need to worry about it. 

EOS, WyoFile and Cardinal Press have all asked in the last two weeks.

**Comment by gamebits** [comment]
Energy News Network is also asking for this feature.

**Comment by yogeshbeniwal** [comment]
Most of the free social sharing plugins either get abandoned over a period of time or paid one has unnecessary extra features for publishers. May be it's time to have a social sharing modules inbuilt in newspack plugin.

**Comment by allykmyta** [comment]
TofSD have also requested this feature.

**Comment by dnalla1928** [comment]
Adding CTMirror.

**Comment by laurelfulford** [comment]
This has been resolved in Jetpack in https://github.com/Automattic/jetpack/pull/22579 -- it will be available in Jetpack 10.7, but it already available in the Jetpack beta running on hosted Newspack sites, so I'm going to mark this as resolved!
