### ISSUE TITLE
Filter backend posts by author

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-plugin#1182]
**Is your feature request related to a problem? Please describe.**
Many Newspack publishers work with large editorial staffs. The WordPress backend offers a means for filtering by authors (`/wp-admin/edit.php?author_name=kgagne`) or by post status (`/wp-admin/edit.php?post_status=draft&post_type=post`), but there's not an inbuilt mechanism for combining those search terms, such as all drafts by a particular author. The current solution is to manually combine the search parameters into a hand-crafted URL (`/wp-admin/edit.php?author_name=kgagne&post_status=draft&post_type=post`).

**Describe the solution you'd like**
A dropdown that exists alongside core's existing the "Dates" and "Categories" dropdowns on the `edit.php` screen.

Dropdown:
<img src="https://user-images.githubusercontent.com/12199101/136862446-90fa6928-f97b-40b8-8efe-dba8b76fa7c8.jpg" height="75%" width="75%" />

Author selection:
<img src="https://user-images.githubusercontent.com/12199101/136862447-44c689a2-9109-4f5a-bb52-cd6f9e4df0eb.jpg" height="75%" width="75%" />

**Describe alternatives you've considered**
[Author Filters](https://wordpress.org/plugins/author-filters/) (source of the above screenshots) is a compact plugin that suits this need perfectly. The only limitation is that it does not include Co-Authors Plus (CAP) guest authors in the dropdown. Though ideal, that feature that wouldn't be needed for an MVP.

**Additional context**
OSM has requested this functionality and is satisfied with the above plugin, but I think it would be a welcome feature for all publishers, since filtering by author alone is not as intuitive as it could be.

**Comment by adekbadek** [comment]
Author Filters plugin seems unmaintaned and is very tiny, I think we could add this functionality to the core plugin and also add support for CAP authors.
