### ISSUE TITLE
Plugins screen behavior around premium plugins.

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#119]
**Describe the bug**
Attempting to install a premium plugin on the Plugins screen fails. Additionally, it doesn't make sense to have an 'Install' option for premium plugins, since installation is not possible.

**To Reproduce**
1. Uninstall WooCommerce Subscriptions. Go to Plugins screen.
2. Click on the 'Install' text under WooCommerce Subscriptions. Observe installation fails with 'Failed to install plugin: The plugin directory already exists.' error (even though the directory doesn't exist and it wouldn't know where to install the plugin from anyways).

**Expected behavior**
The 'Install' link should not be present on the Plugins screen for plugins that can't be installed through the plugin manager.

**Comment by JuanchoPestana** [comment]
Hey @claudiulodro, 
Here's a screenshot of the result from the changes I made in PR #230 . 

In this PR, I made the disabled button display the word "Premium", but instead, we could replace it with a link to the premium plugin site or something like that... Let me know your thoughts and if there's anything else I could do to help regarding this issue.

![issue119](https://user-images.githubusercontent.com/17458017/62484529-fe7f5c80-b77f-11e9-89fe-fc235235b4a1.png)
