### ISSUE TITLE
Onboarding: Reader Revenue support all platforms

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-plugin#1301]
At the moment we only have one option during the onboarding.

We should allow the user to choose between Newspack, NHR, and Stripe

![Screenshot 2021-11-25 at 11 09 01](https://user-images.githubusercontent.com/177929/143430845-fab87516-11bc-494d-a828-87f52285f6bd.png)

**Comment by adekbadek** [comment]
Not sure about that – this setup wizard was meant to provide defaults. "Newspack" (which means WooCommerce here) is the default platform.

**Comment by thomasguillot** [comment]
Yes, fair enough. Especially if we prefer publishers to use our Newspack default.
