### ISSUE TITLE
Wizard: Analytics

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#133]
Newspack should provide a simple wizard to easily setup website analytics. 

Initially we will implement support for Google Analytics, which will be setup through Site Kit. 
I've designed a simple wizard that will guide the user to the setup flow for Analytics within Site Kit.

<img width="828" alt="Screenshot 2019-06-27 08 46 22" src="https://user-images.githubusercontent.com/4823744/60276016-0cf07380-98b8-11e9-83b9-10b3be969e30.png">

**Comment by claudiulodro** [comment]
#158
