### ISSUE TITLE
Update list of managed plugins to match new approved/required plugins list

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-plugin#1393]
Now that we've updated our [list of approved plugins](https://docs.google.com/spreadsheets/d/1cOxvYjn57lV2mNU7ExiP1PRJOERDKoyDfO1I5T46DqY/edit#gid=0) and settled on a new review process, we should update the managed plugin list in the Newspack plugin to match.

My recommendation would be for our [managed plugin list](https://github.com/Automattic/newspack-plugin/blob/master/includes/class-plugin-manager.php#L40) to be slimmed down considerably to only include core Newspack plugins (second sheet in the approved plugins list) and the ones marked as "recommended" in the first sheet.

This should help avoid the situation where new users of Newspack install a bunch of plugins we don't necessarily recommend/require and then these plugins either sit around either installed but inactive or, worse, active but not configured in a way that could lead to performance issues/plugin conflicts/etc.

I'm happy to put a PR together to update this list but wanted to make sure the criteria for required/recommended is clear and that this list feels right before we make the update.

Feedback welcome!

**Comment by yogeshbeniwal** [comment]
@aschweigert Does removal of core Newspack plugin such as Newspack Media Partners and Newspack Supporters plugin from managed/recommended plugin means that they may be obsolete in near future?

**Comment by aschweigert** [comment]
@yogeshbeniwal No, just that we're thinning this list down to only plugins that are used by most/all sites to avoid confusion because we've seen a lot of sites install plugins they don't need and then the proliferation of installed/active plugins causing issues for some sites so we just want to make the list a little leaner/clearer.
