### ISSUE TITLE
OpenID Connect Provider for authentication

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1408]
**Is your feature request related to a problem? Please describe.**
If we are looking at everything (User/Subscription/Newsletter) into WordPress then modern authentication mechanism is an important feature missing to achieve that. Publishers use various other supporting services and they all have its own login methods which need to be centralized.

**Describe the solution you'd like**
Add support for OpenID connect/Oauth 2.0 provider to keep all signup/User info in WordPress and allow other services to use it as single source of information for login.

**Describe alternatives you've considered**
Currently user info and login is scattered at multiple places.

**Comment by adekbadek** [comment]
Could you please elaborate on that? What would be a user story that we don't currently support. 

>  Currently user info and login is scattered at multiple places.

This is also not understandable to me. Are we talking about site admins/editors logging in, or subscribers etc?

**Comment by yogeshbeniwal** [comment]
@adekbadek In general for a Newspack user, websites provide content and listing purchase via Wordpress, Newsletter via ESP and if publisher is using 3rd party comment platform (E.g. Coral) then that make 3 places where user info is stored. And at least 2 places with login credentials, 1 in Wordpress and other in Comment platform. 

In order to centralize all this, accounts and login need to be first centralized at once place (OpenID Connect proposed in this feature request) and then further enhancement on top of WooCommerce account management can be done to manage services such as newsletter subscription.

**Comment by adekbadek** [comment]
If I understand this correctly, this is about connections to third-party services. Newspack is currently using OAuth (e.g. Google Analytics & Ad Manager) and REST APIs access (e.g. Mailchimp, Stripe). There are currently no plans to change this – nevertheless thank you for the suggestion. I'll close the issue for now.

**Comment by yogeshbeniwal** [comment]
@adekbadek This is for WordPress users (Admin/Editors/Readers) to login with their account on other supporting platforms. For example login into Coral comment using existing WordPress account.
