### ISSUE TITLE
Testing: Consider some form of e2e testing to catch editor crashes resulting from WP updates?

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#1440]
**Is your feature request related to a problem? Please describe.**
In the update from WP 5.8 to 5.9, the editor JS has changed substantially, resulting in some hard crashes due to our code expecting editor data that has changed format or no longer exists in WP 5.9. This is always a risk when a new WP version comes out, so should we consider some kind of e2e testing that we can run to at least catch hard crashes in the editor?

**Describe the solution you'd like**
This might not need to run with every CI job, but could be something we run at the command line when we know a new WP release is imminent.

**Describe alternatives you've considered**
Currently, we manually test our code when a new WP release is expected, but some form of automated testing might make the task quicker.

**Comment by dkoo** [comment]
cc @Automattic/newspack-product

**Comment by adekbadek** [comment]
A _while_ back I was working on a [Newspack e2e test suite](https://github.com/Automattic/newspack-e2e-tests) – I'll revisit that.

**Comment by adekbadek** [comment]
Set up and running. We should be adding more testing scenarios now ([basic donations flow](https://github.com/Automattic/newspack-e2e-tests/pull/9) is in the works)
