### ISSUE TITLE
Test: jest tests are failing

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#1456]
**Describe the bug**
Perhaps since #1368, but I'm not positive. Jest tests are failing with Rules of Hooks errors:

```zsh
  ● A segment with conflicting prompts › renders a conflict notice for conflicting prompts that have no segment

    Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

      23 |
      24 | const Button = ( { className, isQuaternary, href, onClick, ...otherProps } ) => {
    > 25 | 	const history = useHistory();
         | 	                ^
      26 | 	const [ isAwaitingOnClick, setIsAwaitingOnClick ] = useState( false );
      27 |
      28 | 	const classes = classnames( 'newspack-button', isQuaternary && 'is-quaternary', className );
```

**To Reproduce**
1. `npm start && npm run test`
2. Observe tests failing for every component that uses a hook

**Expected behavior**
Tests should pass. We aren't breaking the rules of hooks as far as I can tell, so this may be a dependency issue. 

**Solutions I've tried already**
I tried the following with no change in behavior:

* Tried adding `react-dom@^17.0.2` as a dependency to the project
* Removed `react`, `react-dom`, and `testing-library/react` as dependencies from the project (the latter is included as a dependency in `newspack-scripts` so it's not needed here)
* Added a `resolutions` rule to `package.json`:

```json
"resolutions": {
  "react": "^17.0.2"
}
```

**Note**

See https://github.com/Automattic/newspack-popups/pull/778 to witness the same Jest setup passing without invoking the hooks error.

**Comment by dkoo** [comment]
The fact that I didn't see this until now reminds me that we don't really run Jest tests regularly, only manually. Maybe we should add it as a CI job?

**Comment by adekbadek** [comment]
> The fact that I didn't see this until now reminds me that we don't really run Jest tests regularly, only manually. Maybe we should add it as a CI job?

But it is [a CI job](https://github.com/Automattic/newspack-plugin/blob/54c1b03eb4329e4c115f8cb5e888458ef779c539/.circleci/config.yml#L34-L41), which [is passing](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin/3340/workflows/078142e1-2761-4b6c-bca1-3290ef757288/jobs/15298). I also can't reproduce the error locally. Perhaps I'm missing something, though?

**Comment by dkoo** [comment]
But it is [a CI job](https://github.com/Automattic/newspack-plugin/blob/54c1b03eb4329e4c115f8cb5e888458ef779c539/.circleci/config.yml#L34-L41), which [is passing](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin/3340/workflows/078142e1-2761-4b6c-bca1-3290ef757288/jobs/15298).

Huh, my mistake! Glad to see it's passing in CI.

> I also can't reproduce the error locally. Perhaps I'm missing something, though?

On the current `master`, if I run `rm -r node_modules && npm start`, then `npm run test`, I get the failing tests. @miguelpeixe what do you see? If it's only me we can close this as one of those strange local-environment issues.

**Comment by adekbadek** [comment]
Do you have `node_modules` in `assets/components`? This has caused some local issues for me in the past.

**Comment by dkoo** [comment]
> Do you have `node_modules` in `assets/components`? This has caused some local issues for me in the past.

Aha, that was it! Closing.
