### ISSUE TITLE
Improved compatibility of CAP and Yoast: Author archive indexing

### ISSUE THREAD

**Issue by akmyta** [Automattic/newspack-plugin#1506]
**Is your feature request related to a problem? Please describe.**
Author archives are not being indexed and the `noindex` meta tag cannot be removed.

**Describe the solution you'd like**
Author archives should be indexed.

**Describe alternatives you've considered**
See: https://github.com/Yoast/wordpress-seo/issues/9147#issuecomment-1031868735

**Comment by allykmyta** [comment]
Requested from TRNN

**Comment by akmyta** [comment]
This has also been requested by The Colorado Sun.

**Comment by leogermani** [comment]
Released → https://github.com/Automattic/Co-Authors-Plus/releases/tag/3.5.8
