### ISSUE TITLE
Reader Revenue: Disable automated social media sharing for Woo donation products created on live sites

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-plugin#1507]
**Is your feature request related to a problem? Please describe.**

For sites that have automated social sharing enabled and are live when they activate Reader Revenue, the WooCommerce donation products that we create get shared automatically. 

**Describe the solution you'd like**

Disable social sharing for donation products.

Happened on Plainsman and EastMojo.

**Comment by dkoo** [comment]
Fix merged—closing.
