### ISSUE TITLE
Site Kit crashes when "Back to Newspack" banner is displayed.

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#1529]
**Describe the bug**

Ran across this bug earlier. If the "Back to Newspack" banner is displayed, the Site Kit dashboard crashes hard.

**To Reproduce**
1. Go to Newspack > Analytics. Click the 'View' on the Google Analytics card:

<img width="1320" alt="Screen Shot 2022-02-24 at 2 49 09 PM" src="https://user-images.githubusercontent.com/7317227/155620601-a1b5c75d-9e8c-40e2-ae7b-8190e1a8d8d8.png">

2. It will take you to the Site Kit dashboard, which will crash with a JS error:

<img width="1520" alt="Screen Shot 2022-02-24 at 2 46 26 PM" src="https://user-images.githubusercontent.com/7317227/155620722-591b8cb1-86ae-4059-8c36-e7d17d56593e.png">

3. Click the "Back to Newspack" in the banner. Visit the Site Kit dash directly at Site Kit > Dashboard. Observe it loads fine when the banner isn't there:

<img width="1518" alt="Screen Shot 2022-02-24 at 2 47 00 PM" src="https://user-images.githubusercontent.com/7317227/155620846-8c39e52e-9eaf-46c7-88ef-243d0fca960b.png">

**Comment by dkoo** [comment]
Site Kit has a [callback](https://github.com/google/site-kit-wp/blob/ea26c8b149dc1043ea0cf8c6770b8536697ecf70/includes/Core/Admin/Screens.php#L153) on the `admin_notices` action which removes all other notices. It really doesn't seem to like any elements being inserted within the `#wpwrap` element in the dashboard—I tried moving our handoff banner to the `admin_footer` action and the `wp_before_admin_bar_render`, and both placements still triggered the Site Kit error. Changing the priority of our action callback to `-9998` allowed Site Kit to remove our notice and bypassed the error, but that means our handoff banner isn't visible within Site Kit's UI. Maybe a decent workaround for now?

**Comment by adekbadek** [comment]
Fixed by  #1537
