### ISSUE TITLE
Use presentment currency as per user Location/Country

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1530]
**Is your feature request related to a problem? Please describe.**
Currently amount set in Stripe is charged as it is irrespective of user Location/Country, which results in double foreign exchange fee.

Scenario: A charge of 5 USD for non-USD based countries: Donor pay Foreign Exchange as presentment currency is not in local currency and Stripe account owner for USD to local bank currency payout.

With news website having audiences globally, this may be applicable to most of websites.

**Describe the solution you'd like**
Present presentment currency as local currency equivalent of charged amount, so that donor side Foreign Exchange can be avoided. 

Note: Pls note that i have doubt if its possible while using same product for all users globally. But that's the understanding i am getting while talking to stripe team.

**Comment by adekbadek** [comment]
If I understand the issue correctly, this is about the site charging in currency A while a donor has their card set to currency B, which results in an exchange fee. 

That's out of scope of Newspack, which is made with small & local publishers in mind. Closing, but let me know if I did not understand the issue correctly.
