### ISSUE TITLE
Problem with AMP

### ISSUE THREAD

**Issue by antosavarese** [Automattic/newspack-plugin#1548]
there is a conflict with amp plugin.
in fact when i select standard mode the mobile version of my site (https://www.foodmakers.it) has errors..for example with margins of layoutin mobile version  and with the sidebar position in desktop version
any suggestion for me?

I've last version of the theme newspack

for example see this page
https://www.foodmakers.it/a-trento-tornano-gli-appuntamenti-del-forum-di-vinifera-2022/

the sidebar instead that on the right is down after the content

**Comment by laurelfulford** [comment]
Hi @antosavarese! 

This sounds like an issue we've run into before -- do you have the 'More' section enabled under Jetpack's Share Buttons? 

If yes, removing that should fix the issue for now -- not all of Jetpack's Share functionality includes AMP support, including the 'More' section. Normally any functionality that is not supported by AMP is just stripped out when AMP is enabled, but for some reason when the More section is removed, it leaves a little bit of malformed HTML that breaks the single post layout. 

There is an issue for that in the Jetpack repo here: https://github.com/Automattic/jetpack/issues/12639

Can you please let us know if that does the trick? Thanks!

**Comment by laurelfulford** [comment]
Hi @antosavarese! It looks like you've since disabled AMP, which also works as another work around if you'd like to keep using the 'More' section in the share buttons. 

I'm going to close this issue as resolved, but please let us know if the problem persists with AMP enabled even when the More section is removed from the Share buttons!
