### ISSUE TITLE
Campaigns - Donor landing page is unsaveable

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#1559]
**To Reproduce**

1. Visit Campaigns wizard,
2. Set a "Donor landing page" and save the settings
3. Observe the landing page is not saved

**Expected behavior**

The setting should be saved.

**Comment by yogeshbeniwal** [comment]
Also adding 1 more issue: Donation landing page on Readers Revenue is "Your donations landing page is set up and published." However on Campaings --> Settings page its still shown as set to None. Landing page supposed to be shown in dropdown in this case is a second level page.

**Comment by adekbadek** [comment]
> Donation landing page on Readers Revenue is "Your donations landing page is set up and published." However on Campaigns --> Settings page its still shown as set to None.

These are separate features, not connected: 
- the Donation page set via Reader Revenue is the page where a donor _makes a donation_
- Donor landing page in Campaigns is a page to which the donor is _redirected to after making a donation_ via a third-party site

**Comment by yogeshbeniwal** [comment]
@adekbadek Thank you for clarification. 

Will add that Donor landing page in Campaigns only show first level pages, not second level pages. This may be not so important and urgent to add.
