### ISSUE TITLE
Onboarding: Setup tool should be inaccessible after being completed

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-plugin#1561]
**Is your feature request related to a problem? Please describe.**

Completion of the setup tool unlocks the full menu of Newspack menu items, none of which is the setup tool itself. This is as it should be: all the individual functions of the setup tool are available in various Newspack settings, and there is no need to regain access to the tool itself.

Yet it can still be accessed directly via the URL:

https://example.com/wp-admin/admin.php?page=newspack-setup-wizard#/

![newspack-setup](https://user-images.githubusercontent.com/12199101/158596540-57fbe8b6-d279-453c-9c28-ae4c3d11dbbc.jpg)

Since we have provided links to the setup tool to publishers in Slack, it may be confusing if they click that link and are presented with the impression that their site still needs to be set up.

**Describe the solution you'd like**

Attempts to  access `/admin.php?page=newspack-setup-wizard#/` on a site that has already completed the setup tool should instead redirect to `/admin.php?page=newspack-site-design-wizard`.

**Describe alternatives you've considered**

Three alternatives come to mind:

1. A redirect to the Newspack landing page of `/admin.php?page=newspack`.
2. The setup tool remains accessible, but with a notice/warning that it has already been completed.
3. The setup tool remains accessible, but only to users with an `automattic.com` or `a8c.com` email address domain.

**Additional context**

Discussion in Slack: p1647434558941389-slack-C01C378QWRX

**Comment by yogeshbeniwal** [comment]
> 2\. The setup tool remains accessible, but with a notice/warning that it has already been completed.

IMO Notice/Warning will be a better option.
