### ISSUE TITLE
Consider enabling NTG custom events by default

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-plugin#1607]
As noted in #1606, as we've started seeing data flowing into the new benchmarking tool, many sites don't seem to have enabled the NTG custom events and I'm wondering why this might be...I know they need to have sitekit connected, but assuming they do, is there any reason why we wouldn't want to just enable these events by default instead of requiring publishers to toggle this option 'ON' (which it seems many of them don't do)?

**Comment by adekbadek** [comment]
NTG events [**are** on](https://github.com/Automattic/newspack-plugin/blob/1c279dc3cf1031d95988565cfc041734fb372cd9/includes/wizards/class-analytics-wizard.php#L529) by default, see https://github.com/Automattic/newspack-plugin/pull/1018. Off-by-default was the behaviour [we had](https://github.com/Automattic/newspack-plugin/pull/924) for a while, though.
