### ISSUE TITLE
Currency ordering makes finding a currency frustrating

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#161]
During setup, the wizard asks for currency. The drop down list is very long and the options are 
ordered seemingly pretty randomly, which makes it quite hard to find the currency you are looking for.

1. On a fresh install, go to Newspack Setup
2. Proceed to step 2
3. Observe the currency list on step 2

**Screenshots**
![Screenshot from 2019-07-03 10-06-34](https://user-images.githubusercontent.com/136342/60579268-a3220f00-9d7a-11e9-989f-c31bfb4a83a6.png)

**Expected behavior**

The drop-down list should be ordered alphabetically to make browsing through quickly much easier.

**Comment by claudiulodro** [comment]
Some sort of autocomplete search, [similar to select2](https://select2.org/getting-started/basic-usage) would be ideal, but just having things in the correct order is a good start. :)
