### ISSUE TITLE
Local development hampered by plugin configuration dependencies

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#163]
In a local development environment, Newspack can never be set up because the Jetpack and Site Kit plugins can't be configured using a local URL. While there are ways to expose a local dev environment on a public URL, there are a few problems with that as a solution:

1. It raises the barrier for developers to get set up
2. It exposes the machine to the outside world, which is a security risk
3. Offline development becomes much harder

It is possible, however, to use common markers like the `WP_DEBUG` constant to detect a local development environment and behave differently, allowing testing to proceed without requiring plugins to be setup completely.

**Comment by philipjohn** [comment]
For now I'm using this small plugin:

```
<?php
/**
 * Plugin Name: Newspack Complete
 * Plugin URI: http://example.com
 * Description: Force Newspack to consider setup Complete
 * Version: 0.1
 * Author: Philip John
 */

add_filter( 'pre_option_newspack_setup_complete', function( $value ) {
	return true;
} );
```

**Comment by jeffersonrabb** [comment]
I suggest using [ngrok](https://ngrok.com/) to expose a public URL. This is how I have my local instance set up, and it allows me to connect Jetpack and Site Kit. Both are essential pieces of Newspack, so I'm hesitant to build a workaround which would mean our development environments are missing critical pieces of the puzzle.

**Comment by claudiulodro** [comment]
https://github.com/Automattic/newspack-plugin/pull/277
