### ISSUE TITLE
Ad Manager block does not produce output

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#166]
**Description**
Any code intended to be output by an Ad Manager block does not actually print the ad code. If non-code is entered it prints fine.

**To Reproduce**
1. Go through the Advertising wizard in Newspack to configure Google Ad Manager
2. Add some ad code
3. In a new post, add an Ad Manager block and select the ad code
4. View the post and observe that the code doesn't get included in the HTML

**Expected behavior**
Ad code is printed out as entered into the ads wizard.

**Comment by philipjohn** [comment]
Closing as it turns out this isn't a block problem, it's a problem with the selection of the ad unit in the block controls not registering when there is only one option. Related: https://github.com/WordPress/gutenberg/issues/11270

**Comment by philipjohn** [comment]
@jeffersonrabb This may be the root of the issue you were having. If you only had one ad unit, try adding a second and then re-selecting in the block controls.

**Comment by jeffersonrabb** [comment]
I have multiple ad units in my testing environment, and I've tried testing with different ones to rule out the possibility that the problem was with using the first one in the list. I'm finding that normal markup does get rendered, but the script tags are removed.
