### ISSUE TITLE
Jetpack Calypso handoff during Setup flow

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#170]
When a user sets up Jetpack, they get dropped into the Calypso Jetpack interface on their site after connecting with WordPress.com. We haven't accounted for a handoff within Calypso with the implementation of #105 (our handoff banner). 

We'll need to explore this more once we have a better picture of this aspect of handoff between Calypso UI and Newspack.

The user basically follows these steps: 
1. User clicks on "Configure Jetpack" within the Newspack setup flow
2. User is redirected to WordPress.com to set up an account or connectan existing account with the Newspack website
3. User signs up for a Jetpack plan
4. User lands in WordPress.com Calypso within the Jetpack interface. There they see a success message for successful Jetpack and .com account setup. The user can dismiss the success message remaining in Calypso (see screenshot below).
5. From there the user isn't exposed to a handoff back to Newspack site unless they find their way back to the Newspack site WordPress Admin. 
5.1 Just some related food for thought: Another question that I'm wondering about is, how would the user know when the "Jetpack" configuration is complete? Technically right when the user dismisses the success message in step 5, but they are exposed to the Jetpack checklist as the next step. This implies that they need to continue there. 

_This is what the user sees once they dismiss the "success message" in step 5:_
<img width="1440" alt="Screenshot 2019-07-16 11 11 18" src="https://user-images.githubusercontent.com/4823744/61315214-8397d700-a7bb-11e9-83a8-b440cf760b59.png">

**Comment by estereofonico** [comment]
Im having the same situation, the plugin is looping on this step. Could you please give a hint to continue the installation

**Comment by thomasguillot** [comment]
Jetpack/Calypso is now slightly different and you are redirected to wp-admin (and the handoff) once JP is connected.
