### ISSUE TITLE
Grid components aren't aligned properly 

### ISSUE THREAD

**Issue by jffng** [Automattic/newspack-plugin#171]
**Describe the bug**
Styles targeting the `#wpcontent` containing element push the newspack container off center by 10px and 20px, depending on the size of the viewport. 

This is related to #94 and #130. 

**To Reproduce**
1. Download the Muriel grid chrome extension (https://chrome.google.com/webstore/detail/muriel-grid/heabkjiofmaphebjodoflpglpkdojpmg?hl=en)
2. Navigate to any page with a `muriel-card` component e.g.  `Newspack -> Components demo`
3. Toggle the grid using the extension 

**Screenshots**
![newspack-muriel-grid-before](https://user-images.githubusercontent.com/5375500/60845543-a702c680-a1aa-11e9-9ebe-abf4d418a84e.png)

**Expected behavior**
The card should align to the Muriel grid.

**Comment by jeffersonrabb** [comment]
I believe this is fully addressed in https://github.com/Automattic/newspack-plugin/pull/172
