### ISSUE TITLE
Custom user profile fields

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-plugin#1723]
Some publishers (MTFP, Berkeleyside) use either [Trust Indicators](https://github.com/Automattic/newspack-theme/issues/1803) or [Yoast SEO Premium](https://yoast.com/help/implementing-schema-with-yoast-seo/) plugins to extend the fields available on user profiles. Some common fields are:

* Job title
* Role (staff, freelancer, etc.)
* Employer/Organization
* Short bio
* Phone number

Implementation of these fields is not standardized: currently, 36 sites have Yoast SEO Premium, and only 4 sites use Trust Indicators. However, the need for these fields is broader than that, with some publishers hacking solutions such as changing the display name to be the "Joe Example, Managing Editor". Storing that data as a single string prevents its discrete use elsewhere.

We should [develop our own standard](https://xkcd.com/927/) and build this functionality into Newspack Plugin. These fields can then be supported and displayed by `newspack-blocks`, such as [Author Profile & List](https://github.com/Automattic/newspack-blocks/issues/1166).

In a future state, we should also consider whether Co-Authors Plus and guest authors' profiles would be extended to support these fields. There is an [open issue for CAP to use Yoast's Schema API](https://github.com/Automattic/Co-Authors-Plus/issues/710). If Newspack Plugin employed a similar API, then perhaps CAP could effortlessly plug into either Newspack or Yoast. Such compatibility might also be beneficial to Newspack Blocks, which could be made aware of Yoast's fields, so that the 36 publishers wouldn't need to migrate their existing data from Yoast to Newspack Plugin.

**Comment by margaretschneider** [comment]
Adding a data point: Reveal has also requested the ability to add Job Title in the Author Profile block, which would be supported by these proposed updates to the Newspack plugin.
