### ISSUE TITLE
`is_plugin_active()` check causing fatal error

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#1735]
**Describe the bug**
The current version of the Newspack plugin is throwing the following error:

```
Fatal error: Uncaught Error: Call to undefined function Newspack\is_plugin_active() in /wordpress/plugins/newspack-plugin/1.85.0/includes/optional-modules/class-rss.php:32
Stack trace:
#0 /wordpress/core/6.0/wp-includes/class-wp-hook.php(307): Newspack\RSS::init('')
#1 /wordpress/core/6.0/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/6.0/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /wordpress/core/6.0/wp-settings.php(598): do_action('init')
#4 /srv/htdocs/wp-config.php(82): require_once('/wordpress/core...')
#5 /wordpress/core/6.0/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#6 /wordpress/core/6.0/wp-blog-header.php(13): require_once('/wordpress/core...')
#7 /wordpress/core/6.0/index.php(17): require('/wordpress/core...')
#8 {main}
  thrown in /wordpress/plugins/newspack-plugin/1.85.0/includes/optional-modules/class-rss.php on line 32
```

This only happens when `WP_NEWSPACK_DEBUG` is set to `true`. 

This originally was discovered on the theme demo sites; it's been recreated on a [Jurassic Ninja site](https://difficult-sawfish.jurassic.ninja/), and a localhost test site as well.

**To Reproduce**
1. Run the latest version of thew Newspack Plugin.
2. Add `define( 'WP_NEWSPACK_DEBUG', true );` to your wp-config.php

Related conversation: p1656452081011229-slack-newspack-product.

**Comment by dkoo** [comment]
The offending code: https://github.com/Automattic/newspack-plugin/blob/master/includes/class-plugin-manager.php#L355-L357

I haven't been able to figure out yet why it causes a fatal, though.
