### ISSUE TITLE
My Account: update newsletter preferences

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#1743]
Adding a newsletter preferences update section in WC's "My Account" (`/my-account`) page. The user should be able to update their **selection** of newsletters.

A separate feature would be to update their **email address** that's subscribed to the newsletters. Should the user be able to subscribe different email addresses to different selection of newsletters, or a single (updateable) email address for their selection of newsletters?

**Comment by adekbadek** [comment]
Done for ActiveCampaign in https://github.com/Automattic/newspack-newsletters/pull/891

**Comment by miguelpeixe** [comment]
Mailchimp: https://github.com/Automattic/newspack-newsletters/pull/903

**Comment by adekbadek** [comment]
Done for major ESP, rest moved to a separate issue: https://github.com/Automattic/newspack-newsletters/issues/905
