### ISSUE TITLE
Authentication: Identity Platform Azure AD B2C

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1772]
**Is your feature request related to a problem? Please describe.**
Publishers use various other supporting services and they all have their own local login authentication such as comments.

**Describe the solution you'd like**
With readers features and related data stored in WordPress, integrate logins for all additional platforms used by publishers in one location. i.e. Using [Azure AD B2C](https://azure.microsoft.com/en-us/services/active-directory/external-identities/b2c/)

**Describe alternatives you've considered**
Using WordPress as authentication provider #1408, this is much better (doesn't need extra service) but may need more dev effort.

Updating To Dos after testing Reader Revenue features released so far:

- [ ] Disable Email verification of users, user's email is verified at IDP level
- [ ] Password reset link should use IDP api or redirect to IDP hosted page to trigger password reset
- [ ] Sync account details change such as First Name, Last Name and Email with IDP

**Comment by adekbadek** [comment]
This is out of scope for this project, perhaps a WP plugin could serve this functionality.

**Comment by yogeshbeniwal** [comment]
@adekbadek with recent roadmap announcement for federated websites, does this feature request become in scope?

**Comment by adekbadek** [comment]
No, it doesn't.

**Comment by yogeshbeniwal** [comment]
@adekbadek Thank you. So how it will works with integration between multiple wordpress instances, users will be authenticated with first wordpress as provider and another as client? Asking because currently finalising central user management for multiple brands under one entity.

**Comment by adekbadek** [comment]
That's a great question! We don't yet have an answer though. This will be worked in in first half of 2023, probably.
