### ISSUE TITLE
Synchronising email change w/ 3rd parties

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#1783]
The email address is the only shared data point between the WP instance and Stripe, and it's used to identify users. If the email address is updated in Stripe or on the WP instance, this change should be synchronised.

**Comment by adekbadek** [comment]
For now, the email address in "My Account" is non-editable (https://github.com/Automattic/newspack-plugin/pull/1815)

**Comment by miguelpeixe** [comment]
Shouldn't we store a Stripe user ID as user meta?

**Comment by adekbadek** [comment]
Yes, and the ActiveCampaign, Mailchimp IDs, too.

**Comment by adekbadek** [comment]
Direct Stripe integration has been deprecated.
