### ISSUE TITLE
[Reader Activation] Fire a new action hook with reader-supplied email address at earliest possible moment

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#1791]
**Is your feature request related to a problem? Please describe.**
We have a [`newspack_registered_reader` action hook](https://github.com/Automattic/newspack-plugin/blob/master/includes/class-reader-activation.php#L825) that fires as soon as a reader is registered and authenticated, but there's need for an earlier action hook that fires at the earliest possible moment when a reader supplies their email address. This could potentially happen before registration, or during certain flows that don't trigger a registration, such as:

* A single donation by an anonymous user: this doesn't result in an account registration.
* A successful authentication by a reader who has previously registered.

There are at least two proposed features that will need the supplied email at this moment:

1. The [ActiveCampaign "master list" Newsletters feature](https://github.com/Automattic/newspack-newsletters/issues/896) for Blue Lena, where any reader who supplies an email address should automatically be added to a master AC list for drip campaign and non-newsletter purposes. If a reader makes a single donation or logs into an account that was created before the Reader Activation registration flow existed, we'll need to check the status of that email address and add it to the master list, if it's not already a contact on that list.
2. The [proposed feature for Campaigns](https://github.com/Automattic/newspack-popups/issues/893) to look up readers who are not already known in segmentation data to be newsletter subscribers in the connected ESP, in case they've previously subscribed via other means.

**Describe the solution you'd like**
On any Newspack-controlled flow that begins with a reader supplying an email address, we should fire an action hook with that email address that can be consumed by the other plugins.

**Describe alternatives you've considered**
We could potentially use the existing `newspack_registered_reader` hook when a new registration occurs, but I'm worried this might miss certain reader flows that don't trigger that hook.

**Comment by adekbadek** [comment]
So we'd need a hook (let's say `newspack_reader_email_supplied`) firing when email is processed by:

- registration block
- donation block
- newsletter signup block
- authentication forms (#1754)

> A single donation by an anonymous user: this doesn't result in an account registration.

But [it does](https://github.com/Automattic/newspack-plugin/blob/365aed937ccc8f7b03efe99d0ff3097149a6b37b/includes/reader-revenue/class-stripe-connection.php#L714-L719) – Reader Activation will create an account for any anonymous donation.

**Comment by miguelpeixe** [comment]
Although `register_reader()` is supposed to be the earliest point of email capture everywhere possible, the reader can still end up using `wp-login.php` or WC's "My Account" login form by accident, which we currently do not hook into.

An extra action hook can be added earlier in the `register_reader()`, before some of the validation that returns early. This action hook can be reproduced anywhere we'd need it, including core and third-party plugins hooks.

```php
/**
 * Fires as soon a reader email is known.
 *
 * @param string $email Email address.
 */
do_action( 'newspack_reader_email', $email );
```

**Comment by dkoo** [comment]
> But [it does](https://github.com/Automattic/newspack-plugin/blob/365aed937ccc8f7b03efe99d0ff3097149a6b37b/includes/reader-revenue/class-stripe-connection.php#L714-L719) – Reader Activation will create an account for any anonymous donation.

Ah, that's true of anonymous Stripe donations, but what about donations via WooCommerce?

**Comment by dkoo** [comment]
Seems like the single anonymous donations with WooCommerce as the reader revenue platform are the only missing scenario where the reader isn't immediately registered. Unless I'm missing something, we should register these readers, too. #1795 implements this, which means a new hook will no longer be needed.
