### ISSUE TITLE
[Reader Activation] Sign in link not triggering modal on AMP pages

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-plugin#1792]
Although the "Sign in" link script to trigger the modal is running on AMP Plus it's not working for the desktop link. On mobile viewport, the link works as expected.

Without AMP the link works on both desktop and mobile.

Inspecting the script I could confirm that all the [`triggerLinks`](https://github.com/Automattic/newspack-plugin/blob/717b5b8f20660efd27c2351d60830b288996b8b9/assets/reader-activation/auth.js#L69) are indeed selected on the page and the event listener is attached to the nodes. It looks like AMP, at some point, replaces the nav links DOM nodes and the event listener is no longer attached.

**Comment by adekbadek** [comment]
This is caused by `amp-sidebar` rearranging the DOM. I'll have a look at possible fixes.

**Comment by adekbadek** [comment]
No dice yet. If all else fails the initialisation can be delayed by e.g. 100ms if `amp-sidebar` is detected (`customElements.get( 'amp-sidebar' )`) :/
