### ISSUE TITLE
Adjust Performance wizard screens

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#180]
**Is your feature request related to a problem? Please describe.**
This is related to #141 Performance Wizard. 
We got some good feedback from the Muriel team about the first screen. There is a lot of information on it, it's not structured great, and the informational copy style is currently implemented with a lighter grey text color which questions the emphasis and importance of the information. Basically this is a good opportunity to rethink this screen.

Current implementation:
![screencapture-newstest-ngrok-io-wp-admin-admin-php-2019-07-26-12_25_18](https://user-images.githubusercontent.com/4823744/61973137-9753f200-afa0-11e9-9939-8d800cbc0a2e.png)

**Suggested updates:**
Based on the feedback and the updated management UI we're implementing, I'm proposing the following updates?
- Update title and subtitle on all screens screen (for better context).
- Implement the tabs to separate the AMP information and the Advanced PWA features
- Update copy and text structure on AMP tab screen
- Add sub nav for Advanced PWA features to access the three screens
- Adjust button text Advanced PWA screens from "Continue" to "Save" (if from a technical point we don't need it because it auto saves, except probably Push Notifications, we might not need a button at all)

**Updated designs ([in Figma](https://www.figma.com/file/CFxMAXFD0DxNFcVkDkQw4gLb/Newspack-Plugin-v1?node-id=1039%3A1556)):**

<img width="901" alt="Screenshot 2019-07-26 12 30 45" src="https://user-images.githubusercontent.com/4823744/61973642-bacb6c80-afa1-11e9-9a60-6adf0a9c35f8.png">

_Add to Home screen conditionally shows an image uploader when enabled for adding a favicon:_
<img width="957" alt="Screenshot 2019-07-26 12 35 10" src="https://user-images.githubusercontent.com/4823744/61973857-552bb000-afa2-11e9-86d7-06a4fad7347e.png">

_Offline usage has a simple on/off toggle:_
<img width="946" alt="Screenshot 2019-07-26 12 35 40" src="https://user-images.githubusercontent.com/4823744/61973866-5bba2780-afa2-11e9-9a45-c61caebc592c.png">

_Push Notifications have conditional fields that show only when this feature is enabled:_
<img width="586" alt="Screenshot 2019-07-26 12 36 45" src="https://user-images.githubusercontent.com/4823744/61973873-61177200-afa2-11e9-8083-9a2ef8d1d1a7.png">

**Comment by thomasguillot** [comment]
outdated
