### ISSUE TITLE
"My Account" page logout redirection

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-plugin#1830]
Logging out through the "My Account" page menu redirects to WC's login form.

Probably the homepage would be best since we're not using WC or WP core login forms for reader activation.

**Comment by dkoo** [comment]
Per internal discussion, let's consider this issue closed. https://github.com/Automattic/newspack-plugin/pull/1977 may well be a better approach, but it relies on a WooCommerce bug being fixed, and it would also need further work to show some kind of reader-facing messaging when the logout occurs. Let's close this for now and reopen when https://github.com/woocommerce/woocommerce/issues/24243 gets released.
