### ISSUE TITLE
dashed borders everytime you click a button

### ISSUE THREAD

**Issue by Clicklt** [Automattic/newspack-plugin#1836]
Every time you click on any visual element on the site there is a dashed border that shows for a few seconds.

1. Go to any web site using newspack
2. Click on the logo or menu buttons
3. You can see the dashed border

![InkedSin título](https://user-images.githubusercontent.com/107821423/182508832-34953da2-1dce-418c-bea3-8bd0cb9585da.jpg)
![InkedSin título2](https://user-images.githubusercontent.com/107821423/182508836-c31f1d24-0cff-46be-8581-cccd5848428f.jpg)

I think that those lines should not appear since they can affect the aesthetics of the web page and the user interface.

**Comment by adekbadek** [comment]
This is intentional. A `focus` state helps users who navigate with a keyboard.
