### ISSUE TITLE
Reader Activation: prevent excluding logged-in users from GA in Site Kit

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#1838]
Site Kit disables GA reporting for logged-in users by default:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/7383192/182547676-f2bb26d8-b3bc-4b0b-9032-2737be0b06bf.png">

If Reader Activation is active, this setting should be turned off programmatically.

**Comment by yogeshbeniwal** [comment]
Disabling "All logged-in users", enables second level control "Users that can write posts". With [#824](https://github.com/Automattic/newspack-popups/pull/824) implemented, can disable "Users that can write posts" also.

**Comment by adekbadek** [comment]
Closed in https://github.com/Automattic/newspack-plugin/pull/1960, with the above suggestion implemented.

**Comment by yogeshbeniwal** [comment]
@adekbadek https://github.com/Automattic/newspack-plugin/pull/1960 enables `Users that can write posts`, however https://github.com/Automattic/newspack-popups/pull/824 enables analytics only for user with edit other pages capability. Which one will take priority over other?

**Comment by adekbadek** [comment]
#1960 handles all Analytics - pageviews and events. https://github.com/Automattic/newspack-popups/pull/824 is only about Campaigns-related analytics events. The latter will take precedence, so Campaigns-related analytics events won't ever be sent for admin user sessions.
