### ISSUE TITLE
Reader Activation: Google sign-in button race condition

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#1845]
**Describe the bug**

#1781 has a race condition that results in the "Sign in with Google" button sometimes being inoperable due to the required global not existing by the time the button is rendered. This is still replicable on the current `master`.

**To Reproduce**

1. On a site with Reader Activation enabled and a valid Google connection, set up a Register block in a prompt or in post content.
2. Refresh the page several times and observe that occasionally, but button remains disabled and unclickable.

**Comment by miguelpeixe** [comment]
This is not reproducible without AMP, only on AMP with AMP Plus.
