### ISSUE TITLE
Reader Activation: Login form throws JS errors in AMP Plus

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#1848]
On a site with AMP Plus enabled, submitting the login form with a username and password will throw an AMP-related JS console error:

```
Uncaught (in promise) Error: Only XHR based (via action-xhr attribute) submissions are supported for POST requests.
```

This doesn't seem to prevent the login functionality from working, however.

**Comment by miguelpeixe** [comment]
This looks like an AMP issue. Although it [allows us to not enforce `action-xhr` for `POST` forms](https://github.com/ampproject/amp-wp/pull/6527), it still throws this error when it's identified.

**Comment by dkoo** [comment]
Sounds like a non-issue, then.
