### ISSUE TITLE
Spam account created

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1861]
**Is your feature request related to a problem? Please describe.**
Spam accounts are being created, email accounts used for signup doesn't exist.

**Describe the solution you'd like**
Looking at timestamp of users created, it's a scripted/automated attack. Use CSRF token on frontend wherever it provide interface for reader registration and some kind of rate limiter/access restriction at API level. 

**Describe alternatives you've considered**
- Using Security plugin: Access to /wp-json/wp/v2/users endpoint is throwing error with access restriction but Spam accounts are still created

```{"code":"rest_api_access_restricted","message":"You do not have sufficient permission to access this endpoint. Access to REST API requests is restricted by Security settings.","data":{"status":401}}```

- Disabling Membership --> Anyone can register, but this is a requirement for readers feature for registration

**Comment by adekbadek** [comment]
Thank you for this report! Would you please clarify if this attack uses the WP API to create the users, or the HTML frontend?

**Comment by adekbadek** [comment]
Closing due to lack of response.
