### ISSUE TITLE
Add reCaptcha for WooCommerce to supported plugins

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-plugin#1885]
Now that reCaptcha for WooCommerce is our preferred solution for adding a reCAPTCHA to checkout forms when using WooCommerce-based "Newspack" for Reader Revenue, we should add it to the list of supported plugins for easy install and so it doesn't appear as a rogue plugin in our Health Check feature

**Comment by gamebits** [comment]
> we should add it to the list of supported plugins for easy install

Since this is a premium plugin, listing it in the Newspack plugin manager won't enable a one-click install option like it would for plugins in the wporg repository; instead, it will require manual installation, like WooCommerce Subscriptions and Name Your Price do. Still worth adding, though!
