### ISSUE TITLE
Reader Activation – make ESP synchronisation optional

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#1893]
## As is 

The ESP-synchronisation features (adding contact, updating metadata) are implicit when Reader Activation is enabled. 

## To be 

The ESP-synchronisation should be optional, for publishers who do not wish to use the ESP as a CRM.

**Comment by miguelpeixe** [comment]
The automatic ESP synchronization is currently only supported by ActiveCampaign.
