### ISSUE TITLE
RSS enhancements: include ability to include or exclude by tag

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-plugin#1897]
It's not uncommon for publishers to create tag-based RSS feeds. Right now, RSS Enhancements only allows for customizing by category. Adding the option for tags would allow for more flexibility. 

Requested by Sahan Journal.

**Comment by tmmbecker** [comment]
Duplicate of the issue that was[ imported](https://github.com/Automattic/newspack-plugin/issues/1899).

**Comment by ericdye** [comment]
Fort Worth has also requested this option.
