### ISSUE TITLE
Uncaught TypeError: e.hasAuthLink is not a function

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1914]
**Describe the bug**
Clicking on sign in button in header doesn't show anything and is throwing error in browser console as shown below

![Screenshot](https://user-images.githubusercontent.com/7325107/185144395-9a5332d4-0f85-4be6-9270-f986368af4d7.png)

**Comment by miguelpeixe** [comment]
The `reader-auth.js` being pulled is `ver=1.80.0`. The latest version is 1.89.0.
