### ISSUE TITLE
Site Design: Changing 'settings' deactivates theme

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#1976]
**Describe the bug**
When you change an option on the Dashboard > Newspack > Site Design > Settings tab, the theme gets un-selected. This has happened on publisher sites, and I was able to recreate it on a Jurassic Ninja site and locally. On the Jurassic Ninja and localhost sites, only the Newspack plugin and Newspack Blocks plugins were active.

Changing settings on the Dashboard > Newspack > Site Design > Design tab does not cause the same issue.

**To Reproduce**

1. Navigate to Dashboard > Newspack > Site Design > Settings.
2. Change any of the settings.
3. Click 'Save'.
4. View the front-end of the site.

**Screenshots**

When you navigate to Appearance > Themes, no theme is selected: 

![image](https://user-images.githubusercontent.com/177561/188697132-38aa9071-3dd7-4ad3-ac18-8d302dfff962.png)

When you view the front-end, some of the theme files are loading (to render the HTML), but not the styles:

![image](https://user-images.githubusercontent.com/177561/188697249-aa6c9118-b9b0-41ce-bf9a-e4d6a5580687.png)

When you view the source, CSS files like 'Print' are still loading, but not the theme's main stylesheet -- instead, it has a blank directory for the main style.css file. This happens for the default theme, and all the child themes:

![Screen Shot 2022-09-06 at 10 06 58 AM](https://user-images.githubusercontent.com/177561/188697905-76a087f5-95dd-44ad-b1df-89349b530399.png)

**Expected behavior**

I would expect that the current theme would remain selected. My best guess is saving this screen also saves an empty value for the current theme, but I'm not sure where.

**Comment by gamebits** [comment]
Happens in both PHP 7.4.30 and PHP 8.0.0.
