### ISSUE TITLE
Newspack Analytics do not display in Safari

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-plugin#1986]
The analytics tab is empty when viewed in Apple's Safari desktop browser.

**Describe the bug**

When viewing **Newspack -> Analytics** (`/wp-admin/admin.php?page=newspack-analytics-wizard#/`), only WordPress core's UI loads; the page content itself is blank. This experience is reproducible across multiple Newspack sites.

The only error in the console is

```
[Error] Failed to load resource: the server responded with a status of 404 () (index.module.js.map, line 0)
```

**To Reproduce**

1. Use Safari v15.16.1 or later (or possibly earlier) to log into the backend of any Newspack site.
2. Navigate to Newspack -> Analytics.
3. Observe the blank screen.
4. Navigate to the same page in Firefox
5. Observe the Newspack logo, the three tabs (Plugins, Custom Dimensions, Custom Events), et al

**Screenshots**

Analytics when viewed in Safari:

![np-analytics-safari](https://user-images.githubusercontent.com/12199101/189233105-b05a3e46-a7a0-401b-91a5-79d53e10622f.jpg)

When viewed in Firefox:

![np-analytics-firefox](https://user-images.githubusercontent.com/12199101/189233130-5be2cb77-18b7-4cb5-895a-109978136378.jpg)

**Expected behavior**
The display as seen in Firefox should be evident in Safari as well.

**Comment by adekbadek** [comment]
@gamebits can you verify in Safari private browsing mode? An extension might be blocking the scripts from loading.

**Comment by gamebits** [comment]
I can no longer replicate this issue in Safari, either private or otherwise. 🤷🏼‍♂️

Unless you want to keep this issue open in case of a recurrence, I'm fine marking it as closed.

**Comment by gamebits** [comment]
This happened again tonight. I think it may have been the Ghostery extension causing issues. Turning it off then back on allowed the Analytics panel to load.
