### ISSUE TITLE
Photo credits and captions are funky in Gutenberg

### ISSUE THREAD

**Issue by GrahamWR** [Automattic/newspack-plugin#208]
**Describe the bug**
When images are placed into the body of an article, the photo credit is omitted in the block editor. And in a gallery, the caption is on top of the photo and it blocks part of the image. 

**To Reproduce**
1. Create new article in the block editor
2. Add block and then a gallery
3. Click media library, select the images you want to use then insert gallery

1. Create a new article in the block editor
2. Add a 
<img width="795" alt="Screen Shot 2019-07-24 at 2 25 28 PM" src="https://user-images.githubusercontent.com/52721618/61822457-2c2ee200-ae1f-11e9-9d02-abf19b1aecd8.png">
block and then a new image
3. Click media library, select the image

**Screenshots**

**Expected behavior**
The photo credit should be added to all photo and the text should be underneath the photo

**Comment by thomasguillot** [comment]
The reason why the style for the gallery is different is because the caption would break the vertical alignment/grid of the gallery if it was underneath
