### ISSUE TITLE
Adding featured image gallery in a slideshow format

### ISSUE THREAD

**Issue by GrahamWR** [Automattic/newspack-plugin#209]
**Is your feature request related to a problem? Please describe.**
This is currently not a function that is available in the block editor, only in classic

**Describe the solution you'd like**
The ability to create a slideshow as the featured image for any article

**Describe alternatives you've considered**
Using the classic editor to make it work.

**Additional context**

**Comment by adekbadek** [comment]
Using a slideshow in the position of the featured image is not something supported by Newspack.
