### ISSUE TITLE
Handoff bar improvements

### ISSUE THREAD

**Issue by rickybanister** [Automattic/newspack-plugin#221]
1. Don't show the handoff bar until you've completed the required steps before the handoff is important. In site kit's case, it would be after returning from Google and configuring everything.
2. Customize the language of the handoff banner to be specific to the current flow. Example: `After configuring Google Sitekit return to Newspack in order to complete setup | Back to Newspack`

**Comment by adekbadek** [comment]
Closing for now – handoff banner is less frequently used now that Site Kit & other plugins configuration is not part of the Setup wizard.
