### ISSUE TITLE
Multiple required plugins can be a confusing UI

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#224]
**Describe the bug**
It's not a bug as such, just something I got confused about. Having not looked at it in a while, when I went to the Performance wizard, I got this screen:

![Screenshot from 2019-07-31 12-15-41](https://user-images.githubusercontent.com/136342/62207838-0c526d80-b38d-11e9-80a8-6afe103eb004.png)

I was initially confused by a few things:

1. Why are there two PWA items?
2. Do I need to choose between them?
3. How do I do that?

Of course, knowing what we're doing in the background I soon realised that these two items are just plugins - one installed and active, the other not - and I just need to click "Install".

This made me question why we're even presenting the plugins. The user kind of doesn't need to know that we're installing plugins, they just want it to work. The descriptions don't help either - what's a "feature plugin" and "core" to a normal user?

**Possible Solution**

1. Ideally the user doesn't see this screen at all - we just show a loading screen that lets them know we're setting stuff up and do the plugin installation and activation in the background.
2. We present this screen but simplify it by having a single card with a very simple list of plugins saying "we need to install these, is that ok?" and a button that says "Proceed" or similar

**Comment by philipjohn** [comment]
One other thought, actually - it isn't very clear what the blue tick means (I actually went to click on it) especially as the second plugin doesn't have one.

Given it indicates status improvements to make it clearer might be:

1. Using a tooltip on hover
2. Accompanying text (e.g. "Active")
3. Adding a similar status icon/text to the inactive plugin in the lists too, to show what the difference is

**Comment by jeffersonrabb** [comment]
cc: @rickybanister re: discussions about plugin installation transparency vs. "just works."

**Comment by rickybanister** [comment]
I think the way forward is probably a strange, but happy hybrid of transparency and just works. 

I agree with @philipjohn's second solution. I think the current awkwardness comes from us requiring these plugins, but also asking the customer to opt-in. They don't really have a choice, so we should probably indicate as such in the UI. 

I'd like the messaging here to be something more like (not literally, but this vibe):

'Let's speed up your site and help your audience engage on their mobile device. To do so we need to install some plugins for you and then you'd configure a few settings. Sound good?'

**Comment by rickybanister** [comment]
Adding to this, I had the same kind of experience when going through the advertising set up screen. In that case our plugin is required, the UI to install it is very bland and minimal, and it's really just an impediment to get to the next step of really configuring your advertising. I think the 'install' screens should likely be more under the hood and contained within a mention on a splashier landing/set up screen. I'll work on an illustration of what I mean.

**Comment by philipjohn** [comment]
Did we have some concern about the WP plugin guidelines that led us to want a very deliberate install screen? I just vaguely remember a conversation like that, so thought it might be worth questioning as I don't see anything in the plugin guidelines that we'd come up against if we just silently installed and activated everything.

Not necessarily saying we _should_ do it completely silently, but noting that we probably have the freedom to do what we want, in case that wasn't clear.

**Comment by rickybanister** [comment]
I'm ok with a deliberate screen. It's fine to ask them to click a button and agree very clearly to install another plugin. I just would like to make the page less clinical/transactional and talk more about the value of said plugin. For hosted customers, however, I'd definitely skip this step as I think we'd be fully covered to do whatever we want behind the scenes under our ToS.
