### ISSUE TITLE
Components: Image uploader

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#23]
A link that opens the media modal when clicked and allows uploading and setting of an image.

This component needs some more research around it. There should be existing work that we can piggyback somehow.

Example usage:
<img width="278" alt="add-subscription" src="https://user-images.githubusercontent.com/7317227/56914191-506d6380-6a68-11e9-8fc2-7888d198ade5.png">

Design:
<img width="109" alt="image-uploader" src="https://user-images.githubusercontent.com/7317227/56914194-52cfbd80-6a68-11e9-98d2-c0c2296df9ce.png">

Existing implementations:
- ???

**Comment by sonjaleix** [comment]
@claudiulodro I think this is looking and working great! For implementation, we might want to consider reducing the size of the image thumbnail. See new screen attached. It would be ideal if we could set a max height for the image thumbnail and then show the full image in a small size (not crop to a square). 

<img width="443" alt="subscription-image-uploader-thumbnail" src="https://user-images.githubusercontent.com/4823744/57877084-2e980e80-77d4-11e9-90cf-c540d42e51c3.png">
