### ISSUE TITLE
Form input finesse

### ISSUE THREAD

**Issue by rickybanister** [Automattic/newspack-plugin#231]
The inputs have the right appearance, but the interaction feels different than the Material ones they're based on. Clicking anywhere within the bordered area should focus the input, but currently you must click on the inner focusable input. That leaves a very small hit state. The focus style also seems to be bleeding through from the input (the surrounding border should indicate focus I believe, though we should double-check about accessibility):

<img width="169" alt="Screen Shot 2019-08-05 at 5 46 26 PM" src="https://user-images.githubusercontent.com/437258/62497254-672eff00-b7a9-11e9-82be-76ef1c2efeaf.png">

**Comment by thomasguillot** [comment]
This has been fixed with the new redesign of the plugin

<img width="617" alt="Screenshot 2020-01-03 at 17 18 33" src="https://user-images.githubusercontent.com/177929/71737962-16512e80-2e4d-11ea-8afa-cc34615f5152.png">
