### ISSUE TITLE
Currency handling improvements

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#235]
**Describe the bug**
These issues affect both the plugin and block repos, but I'll just log it all here. 

- When a store is using a currency that has a symbol longer than 1 character, things do not look nice.
- There is no support for currencies displayed after the price (e.g. 20$). The settings/block should take the WooCommerce currency position settings into account.

**To Reproduce**
1. Go to your Reader Revenue settings. Set currency to e.g. Uzbekistani som. Observe formatting on block/donation settings is not good.
2. Go to WooCommerce > Settings > General > Currency position and set currency position on right. Observe block still displays currency on left.

**Screenshots**
<img width="653" alt="Screen Shot 2019-08-07 at 9 31 56 AM" src="https://user-images.githubusercontent.com/7317227/62641044-aec3a100-b8f7-11e9-80fb-27713ef2fc54.png">
<img width="718" alt="Screen Shot 2019-08-07 at 9 32 10 AM" src="https://user-images.githubusercontent.com/7317227/62641046-aec3a100-b8f7-11e9-8040-a81cc56540ba.png">

**Expected behavior**
Natural handling of a wide variety of currency settings.

**Comment by thomasguillot** [comment]
The plugin part has been fixed in #329

**Comment by adekbadek** [comment]
Not reproducible anymore.

**Comment by adekbadek** [comment]
Whoops, not really. It is.
