### ISSUE TITLE
Can't edit most of the options on Newspack plugin

### ISSUE THREAD

**Issue by estereofonico** [Automattic/newspack-plugin#2380]
*** 
From version 1.92.0 to the current 1.109.0, I have had problems editing many plugin administration screens such as the Advertising section, Reader Revenue, Health Check, Campaigns and the Connections section. They show a blank page, do not give an error and it is not possible to identify if it is an incompatibility with another Newspack plugin or any other similar situation.

Could you help me find the solution for this? I have already updated the Newspack plugins such as Ads, Blocks and the templates to their new versions without finding a solution to the white screen. How can I see the options of these screens again?

**Screenshots**
![newspack-04](https://user-images.githubusercontent.com/5197998/228438458-6fcf9c28-0ba0-4cdf-9fd3-850ffc4562cb.png)
![newspack-03](https://user-images.githubusercontent.com/5197998/228438459-e96375af-ac2c-4d89-894c-214ab8554f70.png)
![newspack-02](https://user-images.githubusercontent.com/5197998/228438460-28a42313-71de-4178-a54f-5935003d6223.png)
![newspack-01](https://user-images.githubusercontent.com/5197998/228438461-b2c93bb9-d503-4dc9-8acf-2ab850762a31.png)

Please give me soon advice to solve this. Regards.

**Comment by gusaus** [comment]
We're having similar issues on a couple of self-hosted sites. So far we've been unable to identify the root cause. Curious if @estereofonico or other users and contributors have reported related issues since this issue was posted.

**Comment by gusaus** [comment]
So I ended up disabling browser extensions and that didn't work. Then tried disabling all non Newspack core plugins (still nothing worked). THEN I disabled everything except the Newspack plugin and Gutenberg (still nothing worked). Knowing the core editor was a dependency, I assumed Gutenberg wasn't the cause... but when I disabled, all the screens (aside for a few) were visible again.

So Gutenberg seems to be breaking Newspack (at least on self-hosted sites).

**Comment by gamebits** [comment]
> Knowing the core editor was a dependency, I assumed Gutenberg wasn't the cause

Gutenberg is considered a beta plugin and should not be run on production environments.

When Gutenberg features eventually get rolled into WordPress core, Newspack is tested against those versions and updated to ensure compatibility (see https://github.com/Automattic/newspack-blocks/pull/1553 as an example).
