### ISSUE TITLE
Starter Content: Add editable block template 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#258]
This might not quite be the right repo for this, but it doesn't seem to fall under the Newspack Blocks or theme specifically.

Gutenberg has 'block templates', which is a way to set 'starter content' in the editor for a specific post type: https://developer.wordpress.org/block-editor/developers/block-api/block-templates/

Is it possible to bubble up some kind of control where you could add a block template on a site by site basis? We could start with a default, but it would be nice if an individual site could edit it.

**Comment by thomasguillot** [comment]
Onboarding now lets you pick between 12 different layouts
