### ISSUE TITLE
Consistent notice styling using withWizardScreen notices

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#261]
We have [this sort of notice style available now in withWizardScreen](https://user-images.githubusercontent.com/7317227/64065978-77c86e80-cbc9-11e9-9656-903f9ffa2cdc.png). It would be good to standardize around that style in all of our wizards (e.g. the [notice pictured here](https://user-images.githubusercontent.com/7317227/64190841-181dcd80-ce2c-11e9-965a-4bcfab5610d7.png) should be a green notice). It should be fairly straightforward:
```
<div className='notice notice-success'>This is a success notice</div>
<div className='notice notice-error'>This is an error notice</div>
```

**Comment by claudiulodro** [comment]
If this description isn't clear, feel free to ask questions.

**Comment by thomasguillot** [comment]
Closing this. It's on my radar as part of the redesign of the plugin.
