### ISSUE TITLE
Better error notices

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#263]
**Is your feature request related to a problem? Please describe.**
Currently error notices are way at the top of the screen and are not super noticeable:

<img width="803" alt="Screen Shot 2019-09-05 at 8 29 53 AM" src="https://user-images.githubusercontent.com/7317227/64356695-24cf2c80-cfb8-11e9-9beb-9a486924b664.png">

**Describe the solution you'd like**
Ideally errror notices would be within the Card element or right next to where the error happened so the user notices them better. I think we can achieve this by making `setError` and `getError` utility functions instead of withWizard methods. In `withWizardScreen`, any active errors could be rendered [right above the WrappedComponent here](https://github.com/Automattic/newspack-plugin/blob/master/assets/components/src/with-wizard-screen/index.js#L47).

**Describe alternatives you've considered**
To make it so that errors are located right next to the cause of the error, we could give complete control of them to the actual wizard screen `render` method (e.g. `Intro::render` in the Performance wizard). This would increase our overhead though, so I'd prefer not to need to manage error rendering manually.

**Comment by thomasguillot** [comment]
out-of-date
