### ISSUE TITLE
Unrecoverable Error: "n is undefined" on SEO page

### ISSUE THREAD

**Issue by mcmcghee** [Automattic/newspack-plugin#2642]
**Describe the bug**
The SEO page gives the message "n is undefined". This has been tested in multiple environments with a fresh WordPress/Newspack install. 

Disabling one of Yoast or Jetpack takes you to the screen to activate them. When both are enabled, you get the error.

**To Reproduce**
2. Click on Newspack -> SEO

**Screenshots**
![SEO-Error](https://github.com/Automattic/newspack-plugin/assets/6304027/ad149eee-713c-4ed0-8d93-f49998af8c84)

**Expected behavior**
I expected to be able to modify the SEO options without an error.

**Comment by miguelpeixe** [comment]
Thank you for reporting! This was fixed by #2679 2680
