### ISSUE TITLE
Plugin UI: If it makes sense, add a UI for the WP User Avatar plugin

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#285]
This issue is to track looking into adding some kind of UI for the WP User Avatar plugin. Rough steps include:

* Exploration into some UI options
* Assessing if any make sense for us to add to the Newspack plugin
* Working on actual UI and implementation in plugin.

Some off-the-cuff ideas @jeffersonrabb had include:

> 1) we could somehow allow clicking from Avatars in the Articles block to the page where you can override 
> 2) Something near the author dropdown on posts, 
> 3) Some sort of Contributor Management within the Newspack dashboard or 
> 4) Some kind of catch-all in the Newspack Dashboard  for a variety of integrations that don't exactly fit anywhere else.

We don't have to stick with any of these, but they could be a good starting point for discussion.

**Comment by thomasguillot** [comment]
We don't support WP User Avatar plugin anymore. I'm not sure if it fits in the plugin anyway.
