### ISSUE TITLE
"Missing plugins" notice during initial setup

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#301]
**Describe the bug**

I think @jeffersonrabb first noticed this: When setting up the setup wizard on a fresh site, the notice about missing required plugins and theme will be displayed.

**To Reproduce**
1. Set up a new jurassic.ninja site. Install Newspack plugin and go to the setup.
2. Observe red error notice at top during the setup wizard.

**Screenshots**
<img width="1483" alt="Screen Shot 2019-11-03 at 11 49 16 AM" src="https://user-images.githubusercontent.com/7317227/68089619-62252e80-fe30-11e9-8605-0dd161443665.png">

**Expected behavior**
I think ideally the notice would only display [if Newspack has been set up](https://github.com/Automattic/newspack-plugin/blob/6fdfedd3af544c02328021281f69ba03ea480cdc/includes/wizards/class-setup-wizard.php#L39).

**Comment by kn0wsnothing** [comment]
I'm seeing something similar on jurassic.ninja but the Newspack dialog isn't even coming up, instead I get these two lines at the very top: 

Warning: filemtime(): stat failed for /srv/users/user3c53bf9b/apps/user3c53bf9b/public/wp-content/plugins/newspack-plugin-master/assets/dist/setup.js in /srv/users/user3c53bf9b/apps/user3c53bf9b/public/wp-content/plugins/newspack-plugin-master/includes/wizards/class-setup-wizard.php on line 185

Warning: filemtime(): stat failed for /srv/users/user3c53bf9b/apps/user3c53bf9b/public/wp-content/plugins/newspack-plugin-master/assets/dist/setup.css in /srv/users/user3c53bf9b/apps/user3c53bf9b/public/wp-content/plugins/newspack-plugin-master/includes/wizards/class-setup-wizard.php on line 192

Screenshot attached.
<img width="1276" alt="Screen Shot 2019-12-02 at 14 59 28" src="https://user-images.githubusercontent.com/10720350/69936993-59e60f00-1514-11ea-8302-ac741ef456e1.png">

**Comment by claudiulodro** [comment]
@kn0wsnothing please download and install the latest file named `newspack-plugin.zip` at [the Releases section](https://github.com/Automattic/newspack-plugin/releases). It looks like you've installed the source code which is not compiled (causing those missing file errors you see).

**Comment by kn0wsnothing** [comment]
Got it! I just downloaded directly from the main Newspack page.

**Comment by thomasguillot** [comment]
Should be fixed with #328
