### ISSUE TITLE
Stuck on Page 5 / 7, what to do?

### ISSUE THREAD

**Issue by informerfox** [Automattic/newspack-plugin#312]
Hey, I am new to this Plugin and Theme.

I have a self-hosted Wordpress Website on a Cloud Server.
I've done the part of installing the plugin and theme.

While Setting Up, Page 5 asks to Configure Jetpack Plugin, so I Configure it. After that, I return to the Newspack Setup page but the page is still stuck on Page 5 which says Configure Jetpack Plugin, But I have already configured the plugin.

I refresh the page, but it still shows the same page and doesn't move to Page 6.
Tell me what to do?

Thank You!

**Comment by mattpramschufer** [comment]
I too ran into the same issue.  If you actually go into Admin->Settings->Newspack you can check on the box for debug mode.  That will allow you to skip the Jetpack and SiteKit configuration steps.

**Comment by gusaus** [comment]
> Admin->Settings->Newspack you can check on the box for debug mode. That will allow you to skip the Jetpack and SiteKit configuration steps.

Are Jetpack and Site Kit requirements for self-hosted sites? Is there going to be a way to skip configuration steps 'without' going into debug mode?

**Comment by thomasguillot** [comment]
I can't replicate the issue. This might have been fixed at some point. Feel free to re-open if it's still not working for you.

> Are Jetpack and Site Kit requirements for self-hosted sites?

Yes
