### ISSUE TITLE
Tweets and Instagram embedding not working in instant article

### ISSUE THREAD

**Issue by iamjamilkhan** [Automattic/newspack-plugin#315]
**Describe the bug**
In instant article format of a post seem not embedding tweets and other social networks post. Please provide custom rules for that so tweet render on instant article markups
![Screenshot_20191123-230615_Chrome](https://user-images.githubusercontent.com/56718338/69482806-e40fe280-0e45-11ea-9585-ac56f58d4024.jpg)

**Comment by thomasguillot** [comment]
Closing... not related to Newspack Plugin
