### ISSUE TITLE
Large sitemaps

### ISSUE THREAD

**Issue by alicam** [Automattic/newspack-plugin#319]
**Is your feature request related to a problem? Please describe.**
Large publishers have large sitemaps, and require an index sitemap XML file, linking to subfiles, etc.

**Describe the solution you'd like**
Is it recommended to implement something like this?

https://wpvip.com/plugins/msm-sitemap/

Or is is better to hook into the Yoast SEO plugin, which I believe can handle this too?

**Comment by thomasguillot** [comment]
I'd suggest Yoast
