### ISSUE TITLE
Components: Checklist progress bar

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#32]
A progress bar to indicate how many tasks in the checklist have been completed. 
The progress bar consists of a stepper, and conditionally shows a 'hide completed' toggle with an arrow.  

<img width="824" alt="checklist-progress-bar-1" src="https://user-images.githubusercontent.com/4823744/57169750-df121580-6dc5-11e9-86f5-8611ad3c0653.png">

Once at least one item in the checklist has been completed a 'hide completed' toggle appears
<img width="822" alt="checklist-progress-bar-2" src="https://user-images.githubusercontent.com/4823744/57169761-f0f3b880-6dc5-11e9-90bf-69d16f653221.png">

**Comment by claudiulodro** [comment]
Blocked by #35

**Comment by claudiulodro** [comment]
This components is just going to be part #31
