### ISSUE TITLE
Clarify audience size question

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#320]
In the setup wizard, it's not clear what "Size of your audience" means, especially when considered alongside the question further down of "Monthly unique visitors". For many people "audience" and "visitors" are the same thing. In fact, the former is the very term used by Google Analytics to refer to the visitors to a website.

**Describe the solution you'd like**
If the two questions are substantially different it would be good to change the wording to make clearer what the distinction is. Alternatively, if it's not necessary to have both we should eliminate one of the options.

**Additional context**
This was raised by publishers when they were going through the setup process themselves.

**Comment by thomasguillot** [comment]
Questions removed
