### ISSUE TITLE
Components: List one icon left

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#33]
We will very likely need a standard checkbox with label. 

<img width="537" alt="Screenshot 2019-05-03 17 49 39" src="https://user-images.githubusercontent.com/4823744/57170713-fbb14c00-6dcb-11e9-889a-95568a5533d4.png">

Potential alternative version with second line description and info icon:
<img width="543" alt="Screenshot 2019-05-03 17 49 51" src="https://user-images.githubusercontent.com/4823744/57170724-0c61c200-6dcc-11e9-9e41-3c85687e12a9.png">

**Comment by jeffersonrabb** [comment]
These should be covered by https://github.com/Automattic/newspack-plugin/issues/22 and https://github.com/Automattic/newspack-plugin/issues/24 which are complete (https://github.com/Automattic/newspack-plugin/pull/27 and https://github.com/Automattic/newspack-plugin/pull/25)

**Comment by sonjaleix** [comment]
These are looking pretty good. For me, the tooltip icon isn't aligned horizontally as it should (see screenshot attached) and it seems the margin between the checkbox and the label is a little too wide. Muriel's design has a margin of 28px.

<img width="498" alt="Screenshot 2019-05-16 12 21 43" src="https://user-images.githubusercontent.com/4823744/57877773-d6faa280-77d5-11e9-9ceb-11a75b24fc3f.png">
