### ISSUE TITLE
Components: Accordion

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#34]
This is a very early exploration and will need to be vetted by someone from the Muriel team. The idea is to enable certain functionality and then configure the settings within. This would only work for a very limited number of options, else I would recommend to go to a secondary screen. There might quite likely exist a better UI pattern for a situation like this. 

<img width="402" alt="Screenshot 2019-05-03 17 55 07" src="https://user-images.githubusercontent.com/4823744/57170915-4d0e0b00-6dcd-11e9-97f6-c09de78b88c4.png">

Once enabled the accordion would open to expose the options. The arrow would also open/close it.
<img width="403" alt="Screenshot 2019-05-03 17 55 16" src="https://user-images.githubusercontent.com/4823744/57170930-6a42d980-6dcd-11e9-8eb7-8cf1638adadf.png">

**Comment by jeffersonrabb** [comment]
For reference: 

https://wpcalypso.wordpress.com/devdocs/design/i
https://github.com/Automattic/wp-calypso/tree/master/client/components/accordion

**Comment by sonjaleix** [comment]
We can probably close this issue. So far we're not using an accordion component in Newspack.

**Comment by jeffersonrabb** [comment]
Agreed.
