### ISSUE TITLE
Developer Mode no longer allows skipping Jetpack configuration

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#345]
**Describe the bug**
#277 introduced "developer mode" which allowed for the Jetpack setup to be skipped in a local/test install, by detecting `WP_DEBUG` and replacing the "Configure" button with a "Continue" button during the setup wizard.

At some point though, this has stopped happening - with `WP_DEBUG` defined and true, the setup wizard still requires configuration, preventing Newspack setup in some situations.

**To Reproduce**
1. Set up a JN site: https://jurassic.ninja/
2. Install the latest release of Newspack (1.0.0-alpha.14 as I type)
3. Use SSH to confirm that `WP_DEBUG` is defined and true in wp-config.php
4. Go through the Newspack setup wizard
5. At the Jetpack setup screen you will see the screen below, where the blue button says "Configure" but should say "Continue".

**Screenshots**
![Screenshot from 2019-12-23 14-42-38](https://user-images.githubusercontent.com/136342/71364196-61d52400-2593-11ea-8761-70f80c56c077.png)

**Expected behavior**
The button should say "Continue", allowing the skipping of Jetpack setup.

**Comment by jeffersonrabb** [comment]
This was changed intentionally in https://github.com/Automattic/newspack-plugin/commit/9e9885af7938bcdd091a8269859056bd4ef1ebbd#diff-45841d9f0c7ec4df17d6b32bc94bf056. The constant is now `WP_NEWSPACK_DEBUG`, but to make things easier navigate to `Settings->Newspack` and enable Debug Mode, which will have the same effect.
