### ISSUE TITLE
Components: Stepper

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#35]
An indicator to indicate progress through a linear flow with more than one step. I'm not quite sure what the final UI design of this stepper is. Here are a few I found: 

Example from unified onboarding
<img width="398" alt="Screenshot 2019-05-03 18 17 10" src="https://user-images.githubusercontent.com/4823744/57171236-aecf7480-6dcf-11e9-879d-16f2da7e3f03.png">

Woo onbaording flows
<img width="488" alt="Screenshot 2019-05-03 18 18 26" src="https://user-images.githubusercontent.com/4823744/57171266-f8b85a80-6dcf-11e9-8356-af47bff6cea0.png">

**Comment by claudiulodro** [comment]
How does this differ from #32? Is the stepper just the progress part and #32 the whole bar?

**Comment by claudiulodro** [comment]
I'm going to make the stepper look like the stepper in #32, so we can just use that component everywhere. Seems reasonable to me.

**Comment by sonjaleix** [comment]
> How does this differ from #32? Is the stepper just the progress part and #32 the whole bar?
@claudiulodro I'll connect with Courtney once she's back to find out if there is a unified stepper / progress bar that Muriel is working with. So let's use this one for now.
