### ISSUE TITLE
Unexpected output when the Jetpack plan isn't suitable

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#386]
**Describe the bug**
When a site doesn't have a Jetpack Plan that allows for WordAds, the message printed out contains `,[object Object]`.

**To Reproduce**

1. On a site with Newspack activated and setup, with Jetpack installed and connected but with a Free plan
2. Go to Newspack > Advertising
3. Under the WordAds section you should see the message "Upgrade Jetpack to enable WordAds." with the above 'object' output on the end

**Screenshots**
![image](https://user-images.githubusercontent.com/136342/72550454-abf7af80-388a-11ea-84d1-6cd89dd255e5.png)

**Expected behavior**
The message should not include the `,[object Object]` bit.

**Comment by thomasguillot** [comment]
Fixed in #381
