### ISSUE TITLE
Popups Screen: Edit Buttons

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#405]
**Is your feature request related to a problem? Please describe.**
The Engagement Wizard Pop-ups screen would be more useable if there were edit buttons besides each listed pop-up, so that they can be edited with a single click. Currently you have to click on Pop-ups in the left navigation and click to edit the Pop-up. 

**Describe the solution you'd like**
Add edit button to the right of each Pop-up in the Category Filtering area, even disabled ones.

cc: @thomasguillot

**Comment by thomasguillot** [comment]
I think we can completely rework the Pop-ups tabs in a "v2" and offer more flexibility and better pop-up management within the plugin.

Here's a quick mockup of what this could look like:

![newspack-popup-management](https://user-images.githubusercontent.com/177929/73085683-fe5a5100-3ec6-11ea-8196-22a48a1aaaab.png)

Based on Action Cards we would have a "status" border -- Primary for Sitewide default, Green for active (has categories attached to it), Grey when inactive.

We can use a Notice to warn users that they have inactive pop-ups. We could also use it to warn when a site has X number of pop-ups and it's probably not the best practice.

On the right hand side we have 2 buttons/icons: Category Filtering and More options.

* Category Filtering will toggle a form field token inside the action card.
* More options allows you to toggle on/off a sitewide popup and also to edit and delete the pop-up via a Popover component (like the Toolbar in Gutenberg)

**Comment by jeffersonrabb** [comment]
Rough first pass at this here: https://github.com/Automattic/newspack-plugin/pull/409
