### ISSUE TITLE
Errors in Setup screen

### ISSUE THREAD

**Issue by kosvrouvas** [Automattic/newspack-plugin#414]
Hello, I'm getting the following errors at the setup screen:
`
( ! ) Warning: filemtime(): stat failed for http://test.local/wp-content/themes/apheter-master/assets/dist/setup.js in C:\Users\Mentor\Local Sites\test\app\public\wp-content\plugins\newspack-plugin-1.0.0-alpha.18\includes\wizards\class-setup-wizard.php on line 186`

`( ! ) Warning: filemtime(): stat failed for C:\Users\Mentor\Local Sites\test\app\public\wp-content\plugins\newspack-plugin-1.0.0-alpha.18/assets/dist/setup.css in C:\Users\Mentor\Local Sites\test\app\public\wp-content\plugins\newspack-plugin-1.0.0-alpha.18\includes\wizards\class-setup-wizard.php on line 193`

Install:

![εικόνα](https://user-images.githubusercontent.com/3307723/73453498-ce062d00-4374-11ea-8b9c-c5dc5218003d.png)

**Comment by kosvrouvas** [comment]
Bump

**Comment by thomasguillot** [comment]
I cannot replicate this issue. Is this still happening?

**Comment by thomasguillot** [comment]
Closing for now... feel free to re-open if needed.
