### ISSUE TITLE
Rethink the SEO Wizard

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-plugin#425]
**Is your feature request related to a problem? Please describe.**
Currently the SEO Wizard doesn't bring much value.

![1 seo-wizard-old](https://user-images.githubusercontent.com/177929/73863104-7ade1f80-4837-11ea-9bb8-453af9f5acc1.png)

* The configure buttons are simply handoffs to Yoast and Jetpack.
* Do we really need a link to Jetpack here?

**Describe the solution you'd like**

Have some basic settings for Yoast with an "Advanced setting" handoff if needed.

![2 seo-wizard-new](https://user-images.githubusercontent.com/177929/73863018-4ff3cb80-4837-11ea-8934-3ea07459ee07.png)
_Note: the page should be using tabs to organise the content but for the purpose of this screenshot all the content is being displayed._

**Comment by jeffersonrabb** [comment]
For Title Separatorm should we be opinionated about the best options and present only those? Newspack UI needn't present options that we consider suboptimal. If the user wants the full range of possibilities they can always use the Yoast dashboard, which we can link to.

**Comment by thomasguillot** [comment]
> For Title Separator should we be opinionated about the best options and present only those? Newspack UI needn't present options that we consider suboptimal. If the user wants the full range of possibilities they can always use the Yoast dashboard, which we can link to.

Sounds good!

**Comment by jeffersonrabb** [comment]
> Sounds good!

Which separators do you like?

**Comment by jeffersonrabb** [comment]
In some of these cases, we may be able to use one Newspack Plugin field to control similar settings in different areas of the site. I'm wondering if the Social fields should also be tied to Jetpack Publicize and maybe the Newspack Theme's social menu. What do you think?

**Comment by thomasguillot** [comment]
`-`, `–`, `—`, `•`, `|`

**Comment by thomasguillot** [comment]
> In some of these cases, we may be able to use one Newspack Plugin field to control similar settings in different areas of the site. I'm wondering if the Social fields should also be tied to Jetpack Publicize and maybe the Newspack Theme's social menu. What do you think?

That would be great. What would happen if a user modify the theme's social menu but not on this page?

**Comment by jeffersonrabb** [comment]
> That would be great. What would happen if a user modify the theme's social menu but not on this page?

Good question. What would be the ideal UI?

**Comment by thomasguillot** [comment]
> Good question. What would be the ideal UI?

We could check if it matches, if not, display a notice?

**Comment by jeffersonrabb** [comment]
> We could check if it matches, if not, display a notice?

What happens when the field is changed (or input for the first time)? Do we automatically update all relevant settings? What if they're set, and different? One possible approach would be a checkbox set that controls which settings are linked to the text field, but this runs the risk of being incomprehensible to the user?

**Comment by thomasguillot** [comment]
Maybe it should be a step during the setup, where we then generate a social menu (and activate it) and fill-in the SEO social settings.

**Comment by thomasguillot** [comment]
> Maybe it should be a step during the setup, where we then generate a social menu (and activate it) and fill-in the SEO social settings.

![Screen Shot 2020-02-05 at 18 09 03](https://user-images.githubusercontent.com/177929/73869658-a286b500-4842-11ea-9ec5-949f37e1f6e2.png)
_Quick mockup_
