### ISSUE TITLE
Fatal error activating Newspack Blocks plugin

### ISSUE THREAD

**Issue by mbernaldo** [Automattic/newspack-plugin#427]
I downloaded & installed Newspack to try it out. Trying to activate Newspack Blocks Version 1.0.0-alpha.25, I get the fatal error warning below. I can't tell if I've done something wrong, or something is missing. 

_Warning: require_once(/wordpress/plugins/full-site-editing/0.19/blog-posts-block/class-newspack-blocks.php): failed to open stream: No such file or directory in /srv/htdocs/wp-content/plugins/newspack-blocks/newspack-blocks.php on line 19

Fatal error: require_once(): Failed opening required '/wordpress/plugins/full-site-editing/0.19/blog-posts-block/class-newspack-blocks.php' (include_path='/:.') in /srv/htdocs/wp-content/plugins/newspack-blocks/newspack-blocks.php on line 19_

It leaves me stuck here in the Newspack setup: 
![Screen Shot 2020-02-05 at 2 07 15 PM](https://user-images.githubusercontent.com/41964051/73874073-d650e300-4820-11ea-9b38-067b0fb86f8d.png)

**Comment by thomasguillot** [comment]
I cannot replicate this issue. Feel free to re-open this if it is still happening for you.
