### ISSUE TITLE
Reader Revenue Wizard - 'plugin' should be plural

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#453]
At the top of the Reader Revenue wizard, when you're first setting it up, you have the message "This feature requires the following plugin." at the top, but there are several:

![image](https://user-images.githubusercontent.com/177561/75469299-9b376080-5943-11ea-9c21-616f6b47725c.png)

There are cases where there is only one plugin (like the Advertising Wizard), so this should either check the number and add an 's' if needed, or say "plugin(s)".

**Comment by bmcculley** [comment]
Hi, I would like to take a crack at this one if it's ok? 

@laurelfulford what would be the preferred way to fix this? Appending the 's'  when needed or just having the s in parentheses?

I currently have a patch to add the 's' depending on `requiredPlugins.length`, it's easy enough to switch if the other method is preferred though.

![image](https://user-images.githubusercontent.com/6238704/78094065-9da53400-73a1-11ea-90a9-967b64357e27.png)

**Comment by laurelfulford** [comment]
Sorry for the delayed response, @bmcculley! 

Personally I think the preferred fix would be to conditionally add the `s`, as you've described -- thanks!

**Comment by bmcculley** [comment]
@laurelfulford awesome, thank you. I just opened a pull request with my proposed change.
