### ISSUE TITLE
Reader Revenue Wizard: Tabs not always available

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#455]
When you first run through the Reader Revenue wizard, you only have this one screen:

![image](https://user-images.githubusercontent.com/177561/75475984-a5ab2780-594e-11ea-93bf-e72ae8a21424.png)

The first thing you want to do, though, is set up your Address (otherwise your currency will not be correct). To do this, you have to click Get Started at the bottom (you could set up LaterPay at this point, but configuring the Donate Block with the wrong currency would be hard).

Once you've run through the Get Started screens, if you return to the monitization settings, you see all three tabs:

![image](https://user-images.githubusercontent.com/177561/75475972-a217a080-594e-11ea-909b-db907ce643fd.png)

The address is only needed once, so it makes sense that it's not always the first screen, but is it possible to display the tabs from the first screen, too, or make the path first to set up the address if it hasn't been done yet, just to make sure that's done before someone tries to configure the Donate block?

**Comment by thomasguillot** [comment]
This has been redesigned
