### ISSUE TITLE
Newspack Popups. "Sitewide default" option not visible until it's published

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-plugin#456]
The "Sitewide default" checkbox -- the first option in the Pop-ups settings -- doesn't appear until after the item is published. It needs to be visible from the start. 

1. Install and activate Newspack Pop-ups.
2. Create first pop-up and add sample text.
3. The first item under document settings is "Trigger."
![Screen Shot 2020-02-27 at 12 55 30 PM](https://user-images.githubusercontent.com/48489469/75476903-04799c80-5961-11ea-922f-d2ca8139708e.png)
4. Publish. 
5. The first item under document settings is now "Sitewide default."
![Screen Shot 2020-02-27 at 12 55 41 PM](https://user-images.githubusercontent.com/48489469/75476922-0a6f7d80-5961-11ea-9f3e-f70baaf4d1a2.png)

**Expected behavior**
All options should appear initially.

**Comment by jeffersonrabb** [comment]
Refiled in https://github.com/Automattic/newspack-popups/issues/72
