### ISSUE TITLE
Site Kit Configured Check No Longer Accurate

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#460]
**Describe the bug**
The Site Kit configuration check reports true always. This is probably due to a recent change in Site Kit, making our check out of date. 

**To Reproduce**
1. Spin up new Jurassic Ninja instance.
2. Install latest Newspack release.
3. Step through Set Up Wizard.
4. When you reach the Site Kit screen it will indicate that it is configured even though it is not.

**Screenshots**

**Expected behavior**

**Comment by thomasguillot** [comment]
Might have been fixed at some point. I can't replicate the issue.
