### ISSUE TITLE
Newspack Plugin (sometimes) treated as unsupported plugin

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#487]
**Describe the bug**
When installing a plugin, WP assigns a folder name with a random string (e.g. `newspack-plugin-3RtygT`), and later renames it to the proper name (e.g. `newspack-plugin`). Sometimes though, that folder name update does not happen - I don't know how to reproduce this error. This causes Health Check to report Newspack plugin as an unsupported plugin:

![image](https://user-images.githubusercontent.com/7383192/76873649-529e0380-686e-11ea-82e1-6b7212efbac0.png)

This check happens in `get_unmanaged_plugins` function:

https://github.com/Automattic/newspack-plugin/blob/ad97de1551ae51981cd714eb62d319186e023408/includes/class-plugin-manager.php#L456-L467

**Comment by thomasguillot** [comment]
Fixed: https://github.com/Automattic/newspack-plugin/pull/1033
