### ISSUE TITLE
Use Gutenberg SVG Element Drop-Ins For Better Accessibility

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#49]
@wordpress/components has a few SVG-related classes (SVG, Path, G) that offer improved accessibility. They're used pretty regularly for block icons and other assets: https://github.com/WordPress/gutenberg/tree/master/packages/components/src/primitives/svg

It may be a good idea to implement these in form components that contain SVG icons and other assets.

**Comment by claudiulodro** [comment]
We're using these components for Newspack logos and other stuff around the plugin.
