### ISSUE TITLE
Can't change the size of a GIF block

### ISSUE THREAD

**Issue by kn0wsnothing** [Automattic/newspack-plugin#490]
**Is your feature request related to a problem? Please describe.**
I want to insert a GIF hosted on Giphy using the GIF block. But the GIF is very big (size of image) and destroys the pretty formatting of my post.
**Describe the solution you'd like**
An option to change the size of the block and/or how large the GIF is displayed
**Describe alternatives you've considered**
Inserting GIF as an image, but they tend to be quite large and compressing them takes time away from other tasks PLUS they never look as good when compressed.

**Additional context**

**Comment by laurelfulford** [comment]
Thanks for reporting this, @kn0wsnothing!

This block is coming from the Jetpack plugin, so I've created a copy of this issue in that repo (https://github.com/Automattic/jetpack/issues/15889). I'm going to close this copy of the issue, but if you have any questions at all about this, please let me know!
