### ISSUE TITLE
Error installing plugin from repo (and release).

### ISSUE THREAD

**Issue by joseffb-mla** [Automattic/newspack-plugin#505]
**Describe the bug**
I am trying to get a demo up onto a clone of our MU environment sandbox.
I am running into a React render error with the following error:

```
The above error occurred in the <WithStyles(ForwardRef(SvgIcon))> component:
    in Waiting (created by PluginInstaller)
    in div (created by PluginInstaller)
    in div (created by PluginInstaller)
    in PluginInstaller (created by InstallationProgress)
    in InstallationProgress (created by WrappedWithWizardScreen)
    in div (created by Card)
    in Card (created by WrappedWithWizardScreen)
    in div (created by Grid)
    in Grid (created by WrappedWithWizardScreen)
    in WrappedWithWizardScreen (created by Context.Consumer)
    in Route (created by SetupWizard)
    in Router (created by HashRouter)
    in HashRouter (created by SetupWizard)
    in SetupWizard (created by WrappedWithWizard)
    in div (created by WrappedWithWizard)
    in WrappedWithWizard
```

I have composer installed and NPM install, with a yarn build.

**To Reproduce**
1. compile composer and npm
2. yarn build
3. enable plugin in site.
4. Wizard gets error.

**Screenshots**
![Screen Shot 2020-04-03 at 3 10 19 PM](https://user-images.githubusercontent.com/44980627/78396420-55faf400-75bd-11ea-92ba-7cb431d37210.png)

**Expected behavior**
Expected wizard to start.

**Comment by adekbadek** [comment]
Cannot reproduce, and this is quite outdated. Please ping me if the issue is reproducible, and add information about what machine & OS are used.
