### ISSUE TITLE
Broadstreet Zones integration 

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#508]
**Is your feature request related to a problem? Please describe.**
When publishers use Broadstreet with Newspack it works well - the Broadstreet plugin connects fine and allows publishers to set up their ads using the widget and shortcode. However, there are global ad positions defined in the theme that are not available to publishers using Broadstreet.

**Describe the solution you'd like**
When a publisher using Broadstreet goes to Newspack > Advertising > Global Settings the "Ad Provider" drop down should include Broadstreet if the plugin is active and set up. Then, in the "Ad Unit" drop down, the available Broadstreet "Zones" should be available.

**Comment by jeffersonrabb** [comment]
I've re-filed in Newspack Ads: https://github.com/Automattic/newspack-ads/issues/37.
