### ISSUE TITLE
Can't finish setup in private network

### ISSUE THREAD

**Issue by cgomezed** [Automattic/newspack-plugin#513]
**Describe the bug**
Can't finish setup in local test site because jetpack can't work on private network and Newspack not continue setup with jetpack in developer mode

**To Reproduce**
1. Instal Newpack plugin
2. Setup

**Expected behavior**
Finish setup

**Comment by jeffersonrabb** [comment]
Hi @cgomezed, if you navigate to Settings->Newspack you'll see a `Debug Mode` checkbox. Checking this causes setup to proceed without requiring that Jetpack and Site Kit be connected. This should resolve your issue.

![Screen Shot 2020-04-23 at 11 26 21 AM](https://user-images.githubusercontent.com/1477002/80117517-48e67a80-8555-11ea-882a-2cbddd12a2f2.png)
