### ISSUE TITLE
Add Google Analytics tracking to social share icon links

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#527]
**Is your feature request related to a problem? Please describe.**
Many publishers use GA tracking URLs to more accurately monitor where traffic to their site originates. For example, when sharing an article on Twitter they may use a link like this:

`https://example.com/2020/05/07/you-wont-believe-how-this-website-tracks-visitors/?utm_source=twitter&utm_medium=social&utm_campaign=tweet`

This helps the publisher to see when visitors originated from their own tweets of articles. This is important for measuring the relative success of social media efforts, including when running experiments.

When visitors use the social share icons to share articles to their own social media profiles, however, no such tracking information exists which means the traffic may not be properly associated with originating from that social media platform, or indeed as a result of having the social share icons active.

**Describe the solution you'd like**
Publishers should be able to enable GA tracking parameters in social share icons. Ideally, default values are provided for the parameters as below, but can be overridden by publishers as required.

Default parameters and values:

* utm_source: twitter|facebook|instagram|etc
* utm_medium=social
* utm_campaign=social-share-icons

**Describe alternatives you've considered**
This could probably be added to Jetpack itself, if we think the need is wide enough.

**Comment by claudiulodro** [comment]
GA tracking of social share icons is automatically added as part of our News Consumer Insights integration
