### ISSUE TITLE
Support prompt when adding a plugin

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#532]
**Is your feature request related to a problem? Please describe.**
There is a lot to consider when using plugins alongside Newspack. Compatibility and performance concerns are probably significant but there are many others, all considered by our research methodology. This is why we encourage publishers to come to us with feature requests first. However, that message doesn't always permeate at the time a publisher decides to try out a new plugin, or reinstall something used previously. This can cause issues with breaking features, performance degradation and in the worse case scenario, downtime.

**Describe the solution you'd like**
Each time a publisher seeks to use the Add New Plugin functionality in WordPress they are reminded of the suggestion to consult the Newspack team first, via some sort of interrupting modal. They are given the opportunity to get in touch via a ticket to ask about the best way to implement the feature they're looking for. The friction of interrupting the installation process to show this message will help to ensure the publisher is fully aware of the options to lean on Newspack's experience and expertise.

**Describe alternatives you've considered**
An admin notice might provide the same reminder, but as there can be many of these they can be overlooked. It also doesn't introduce friction into the plugin installation process, which is important for encouraging publishers to get in touch.

**Comment by adekbadek** [comment]
Related: disabling plugin editing https://github.com/Automattic/newspack-plugin/pull/1125
