### ISSUE TITLE
DISALLOW_FILE_MODS restricts access

### ISSUE THREAD

**Issue by bbertucc** [Automattic/newspack-plugin#543]
**Describe the bug**
If `DISALLOW_FILE_MODS` is active, the newspack settings cannot be accessed. 

**To Reproduce**
Add `define('DISALLOW_FILE_MODS',true);` to wp-config.php. Try to access Newspack settings. You'll see the error "Sorry, you are not allowed to access this page."

**Expected behavior**
We want to keep the server in sync with our repo, so we need `DISALLOW_FILE_MODS` to make sure admins don't mess with server files. We expect to use all the Newspack settings with fallback messages telling us what needs to be manually updated because `DISALLOW_FILE_MODS` is active.

**Comment by zhickson** [comment]
Hey there, can also confirm this is an issue I've just run up against. Any updates on this issue?

**Comment by adekbadek** [comment]
Fix is ready in https://github.com/Automattic/newspack-plugin/pull/1602
