### ISSUE TITLE
Component: Required plugins

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#55]
We'll need a component to use in our wizards that takes a list of required plugins, and tries to install/activate all of the required plugins. It should probably display some sort of spinner while this is going on with a generic message (e.g. "Preparing required plugins"). If the plugins are unable to be installed/activated (e.g. because an uninstalled premium plugin is required), it should display and/or return some sort of useful error message. Some new handling will need to be implemented in the Plugin Manager class to account for premium plugins that cannot be installed, and likely some new functionality will be needed to process a list of required plugins (unless that is done all in JS using our existing plugin management endpoints).

#### Example use case:
1. When the Subscriptions wizard is first loaded, this component checks to make sure WooCommerce, WooCommerce Subscriptions, etc. are installed/active.
2. If the required plugins are not installed/active, it should install and activate them where possible.
3. If WooCommerce Subscriptions is not installed, it cannot be automatically installed since it's a premium plugin. The Wizard should display a useful error message and prevent the user from going forward. If plugin requirements are met and all plugins are installed/activated, the wizard should proceed as normal.

#### Design

TBD. @sonjaleix, thoughts?

**Comment by sonjaleix** [comment]
Here is a first draft of various states of the required plugin "cards" within the wizard. We might not necessarily need the yellow warning label for outdated plugins, if we're trying to utilize auto-updating of plugins.
<img width="519" alt="Screenshot 2019-05-24 11 07 31" src="https://user-images.githubusercontent.com/4823744/58345432-945c4a00-7e15-11e9-9eca-a8b5c0c1a293.png">

**Comment by claudiulodro** [comment]
#69
