### ISSUE TITLE
Site Kit Authentication Error Leads To Hard Crash In Campaign Analytics Wizard

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#550]
**Is your feature request related to a problem? Please describe.**
While testing [Campaign Analytics](https://github.com/Automattic/newspack-plugin/pull/516), on one occasion I got a hard crash ("Unrecoverable Error" `Modal`) related to Site Kit authentication. Normally hard crashes are considered useful because they reveal significant errors or misconfigurations, but in this case the problem was a normal error in another plugin and it may make sense to handle gracefully with messaging suggesting the corrective action. I'm not certain what caused the error — it could have been token expiration, or it could have been related to Analytics property switches which were a normal part of testing the branch.

Here is the error from the log:

```
PHP Fatal error:  Uncaught Google\Site_Kit_Dependencies\Google_Service_Exception: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Invalid Credentials",
        "domain": "global",
        "reason": "authError",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED"
  }
}
 in /srv/www/wordpress-simple/public_html/wp-content/plugins/google-site-kit/third-party/google/apiclient/src/Google/Http/REST.php:92
Stack trace:
#0 /srv/www/wordpress-simple/public_html/wp-content/plugins/google-site-kit/third-party/google/apiclient/src/Google/Http/REST.php(74): Google\Site_Kit_Dependencies\Google_Http_REST::decodeHttpResponse(Object(Google\Site_Kit_Dependencies\GuzzleHttp\Psr7\Response), Object(Google\Site_Kit_Dependencies\Guzzle in /srv/www/wordpress-simple/public_html/wp-content/plugins/google-site-kit/third-party/google/apiclient/src/Google/Http/REST.php on line 92
```

**Describe the solution you'd like**
Graceful handling, messaging about Site Kit configuration errors with suggested steps to correct.

**Comment by jeffersonrabb** [comment]
Update: this error will occur if the current user has not authenticated with Site Kit. So, if another user properly authenticated Site Kit the error will still occur even though the site is set up.

**Comment by thomasguillot** [comment]
Can't replicate anymore
