### ISSUE TITLE
NTG events: user interaction

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#561]
Add user interaction-related Google Analytics events for AMP and non-AMP pages, as described in the [NCI Playbook](https://newsinitiative.withgoogle.com/training/states/ntg/assets/ntg-playbook.pdf).

Events to add:

* Comment
* Push subscription
* Add to homescreen

**Comment by dkoo** [comment]
Of these three event triggers, only commenting is supported by current Newspack and AMP functionality.

* Comment: This event will be triggered when a user submits the comment form.
* Push notification subscription: This functionality is not yet supported by Newspack. We will revisit when it is: https://github.com/Automattic/newspack-plugin/pull/417
* Add to homescreen: This is PWA functionality and should be supported by Newspack, but tracking it is not currently supported in AMP analytics. There's an open issue suggesting that it's still being worked on: https://github.com/ampproject/amphtml/issues/7508

**Comment by yogeshbeniwal** [comment]
> * Add to homescreen: This is PWA functionality and should be supported by Newspack, but tracking it is not currently supported in AMP analytics. There's an open issue suggesting that it's still being worked on: [Add to homescreen event on AMP-Analytics ampproject/amphtml#7508](https://github.com/ampproject/amphtml/issues/7508)

@dkoo It seems amp feature won't be added anytime soon. Can only non-amp events be added first.

**Comment by dkoo** [comment]
@yogeshbeniwal I would suggest using the event filtering functionality to add support for now. In the meantime I'll reopen this issue so we can look into supporting those events natively.

**Comment by yogeshbeniwal** [comment]
Thank you @dkoo. Meanwhile code snippets for this will help too.

**Comment by adekbadek** [comment]
There's no clear way to implement this now (the [AMP issue](https://github.com/ampproject/amphtml/issues/7508) has been abandoned). Added this the discussion here: https://github.com/Automattic/newspack-plugin/discussions/1641
