### ISSUE TITLE
Add support for shortcodes in global ad positions

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#570]
**Is your feature request related to a problem? Please describe.**
Some publishers have very simple advertising needs - using simple images and links for locally-sold adverts. In this situation it's harder for them to take advantage of the pre-defined ad placements in the Newspack theme.

**Describe the solution you'd like**
Many of the plugins (such as AdRotate) use a simple system of shortcodes to allow ads to be placed throughout the site.

We could cater for this by adding a "Shortcode" option to the "Ad Provider" drop down. When selected, a text box will be provided for the publisher to paste in the required shortcode.

**Describe alternatives you've considered**
I did originally imagine a specific integration for plugins like AdRotate, but this would naturally limit to only that plugin when some publishers might want to use an alternative. We'd like for folks to use GAM, but that's not always desirable or feasible.

**Comment by claudiulodro** [comment]
Now that we have above and below header widget areas, do we need this feature? All of the global ad positions are also available as widget areas.
