### ISSUE TITLE
Managed Newspack Wizard Crash If Jetpack Not Connected

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#576]
**Describe the bug**
If Jetpack is not connected, the Managed Newspack Wizard crashes when opened.

**To Reproduce**
1. On a test site, configure the `NEWSPACK_STRIPE_MODE` and `NEWSPACK_STRIPE_PLAN` keys. 
2. Disconnect Jetpack.
3. Navigate to the Managed Newspack Wizard.
4. Observe the crash.

**Screenshot**
<img width="1234" alt="Screen Shot 2020-07-07 at 5 35 16 AM" src="https://user-images.githubusercontent.com/1477002/86761094-b877ec00-c013-11ea-8330-002a4e1abb9b.png">

**Expected behavior**
Jetpack connection is required to fetch Stripe data, so I don't see a way to avoid this situation completely. However, there should be a clear, actionable error as opposed to the generic unrecoverable.

**Comment by thomasguillot** [comment]
Out-of-date
