### ISSUE TITLE
NTG Events: Disqus and Coral comments

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#587]
#582 implemented NTG event triggers for standard WP comment form submissions. Some Newspack sites use Disqus or Coral to manage comments. Look into whether we can implement NTG event triggers for these, too.

**Comment by yogeshbeniwal** [comment]
@dkoo checking if this is still in pipeline for Coral.

**Comment by dkoo** [comment]
Hi @yogeshbeniwal, this issue has been iceboxed, so while it's still an open issue, we don't have a timeline for tackling it.

**Comment by yogeshbeniwal** [comment]
@dkoo Thanks for clarification. Most of the established publishers i have seen so far uses Disqus/Coral or other 3rd party commenting system.

**Comment by adekbadek** [comment]
See discussion in https://github.com/Automattic/newspack-plugin/pull/1219 – a filter can be used to add NTG events.
