### ISSUE TITLE
Style: Wizard flex behavior

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#591]
In certain instances, elements with horizontal flex positioning get cut off. We saw this happening in https://github.com/Automattic/newspack-plugin/pull/588#issuecomment-661959587 where it looks like this:

<img width="607" alt="Screen Shot 2020-07-21 at 10 20 53 AM" src="https://user-images.githubusercontent.com/2230142/88080141-e2fd9500-cb3b-11ea-94e9-6d87ca6db400.png">

Confirmed that this happens on all browsers, but not for all users, strangely.

**Comment by adekbadek** [comment]
[Closed](https://github.com/Automattic/newspack-plugin/pull/588#issuecomment-662009766) by https://github.com/Automattic/newspack-plugin/commit/47e4b91c8100c7c76bff3450bc32e3d54f71b60e
