### ISSUE TITLE
"Not right now" wizard button points to a potentially invalid URL

### ISSUE THREAD

**Issue by clevijoki** [Automattic/newspack-plugin#602]
**Describe the bug**
If you click "Not right now" on the setup wizard, it goes to an invalid url if wordpress is in a sub-directory (we are using bedrock which installs wordpress into a /wp sub-folder)

If I was to guess it seems to just be going to "/wp-admin" vs using the admin_url() call to find the url.

**To Reproduce**
1. Install wordpress into a sub-directory
2. Install Newspack
3. Press 'Not right now' on the Newspack setup wizard.

**Expected behavior**
Back button goes to a valid URL

**Comment by thomasguillot** [comment]
The "Not right now" button has now been removed from the Wizard Setup.
