### ISSUE TITLE
Sort order of dashboard items in Newspack and Customizer

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#613]
**Is your feature request related to a problem? Please describe.**
Somewhat related to #612, @iamstevebeatty mentions that the sort order of the cards in the Newspack wizard and the order of the theme options in the Customizer seem somewhat random. I'm opening this issue to start a discussion about re-sorting the menu items in a more logical way, or at least writing out the current logic (if there is any) we can better explain to our customers.

**Describe the solution you'd like**
Sort order based on some kind of functional logic.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by adekbadek** [comment]
Closing as stale. I don't think sorting would improve the dashboard a lot – best if there was some hierarchy there.
