### ISSUE TITLE
Notice: register_rest_route was called incorrectly

### ISSUE THREAD

**Issue by tongdaitructuyen** [Automattic/newspack-plugin#652]
**Describe the bug**
Notice: register_rest_route was called incorrectly. The REST API route definition for newspack-blocks/v1/video-playlist is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /home/public_html/wp-includes/functions.php on line 5225

**To Reproduce**
- Wordpress 5.5

**Comment by thomasguillot** [comment]
Moved to https://github.com/Automattic/newspack-blocks/issues/799
