### ISSUE TITLE
Mailchimp API key cannot be saved

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#653]
**Describe the bug**
When attempting  to set the Mailchimp API key, there is no button to save it and it doesn't auto-save when editing the field.

**To Reproduce**
1. Log in to a Newspack site that has the Mailchimp for Woocommerce plugin active
2. Go to Newspack > Engagement
3. In the newsletter tab, observe that there is a "Enter your Mailchimp API key" field
4. Enter any value
5. Observe that there is no way to save your entry, and it does not happen automatically
6. Refresh the page to confirm no save happened in the background, or by watching the requests

**Screenshots**
![image](https://user-images.githubusercontent.com/136342/91841209-dcd5fa80-ec49-11ea-942b-7e5da1ea5dbb.png)

**Expected behavior**
There should be a button to save any edits, or an autosave with some kind of saving/saved indicator.

**Comment by thomasguillot** [comment]
Fixed
