### ISSUE TITLE
Select styles in Gutenberg 9

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#667]
#664 has addressed more pressing changes to selects, but still some issues remain. One thing I've caught is that `select`s are pretty different:

On `8.8.0` (nice):

![image](https://user-images.githubusercontent.com/7383192/93250814-a47b0400-f793-11ea-927a-a0ef524c05ad.png)

On `9.0.0-rc.1` (not so much):

![image](https://user-images.githubusercontent.com/7383192/93250837-aa70e500-f793-11ea-80b3-c5c4b4ec99fd.png)

Note that the change is also on the `8.9.3` version.

cc @thomasguillot

**Comment by thomasguillot** [comment]
Fixed at some point 😬
