### ISSUE TITLE
Campaigns wizards redesign

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-plugin#704]
<img width="1160" alt="v5 - init" src="https://user-images.githubusercontent.com/177929/98974507-e1057a80-250c-11eb-8235-a91b1429562b.png">

<img width="1160" alt="v5 - stuff actived" src="https://user-images.githubusercontent.com/177929/98974510-e19e1100-250c-11eb-84cb-05d61525271a.png">

**Comment by adekbadek** [comment]
All wizards redesign done in #705, only Campaigns wizards redesign left in this issue

**Comment by thomasguillot** [comment]
Partially done and closing this issue since the design is evolving anyway.
