### ISSUE TITLE
Category dimension bundles multiple categories together

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#716]
**Describe the bug**
Having set up a custom dimension with the Category role I'm noticing that the reports in Google Analytics show categories bundled together, separated by a comma. The issue is that this makes the reports harder to interpet when looking at what categories are generating views. It's hard to comprehend without seeing it, so I've added screenshots further down.

**To Reproduce**
1. Create a custom dimension in Newspack (see screenshot below)
2. Create a custom report in Google Analytics to show views by category view
3. Generate lots of totally legit traffic
4. View the report and see something like the screenshot below

**Screenshots**
![Custom dimension set up in Newspack](https://user-images.githubusercontent.com/136342/100766948-1d801400-33f1-11eb-997e-195ce850e61d.png)

![Settings for the custom report in Google Analytics](https://user-images.githubusercontent.com/136342/100767178-5f10bf00-33f1-11eb-9f05-c4907e8df1ae.png)

![Google Analytics report showing custom dimension views](https://user-images.githubusercontent.com/136342/100767093-44d6e100-33f1-11eb-918b-42f400a4620c.png)

**Expected behavior**
In the table of the report each line should only have one category. Using the above example, the first line should be "lichfield news" and likely with a much greater count. Otherwise, it's very hard to see how many page views individual categories generate. How many page views did the "coronavirus-lichfield" category have, given it appears in multiple rows, for example?

**Comment by adekbadek** [comment]
After some exploration, it seems that GA does not handle such custom-dimension-value unbundling. We can use Yoast's [primary category feature](https://yoast.com/help/how-to-select-a-primary-category/) to determine a single category to send, though.
