### ISSUE TITLE
Newspack not working with Wordpress Multisite setup

### ISSUE THREAD

**Issue by jeans** [Automattic/newspack-plugin#717]
**Describe the bug**
Newspack not working with WP multisite setup. I don't know if it's expected to work with multisite at all 

**To Reproduce**
1. Set up WP multisite, upload newspack-plugin, newspack-theme
2. Go to 'wp-admin/network/plugins.php'
3. Activate 'Newspack Plugin networkwide'

> Warning: array_merge(): Expected parameter 2 to be an array, null given in /www/htdocs/domain.tld/wp-content/plugins/newspack-plugin/includes/class-plugin-manager.php on line 635
> 
> Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/domain.tld/wp-content/plugins/newspack-plugin/includes/class-plugin-manager.php:635) in /www/htdocs/domain.tld/wp-includes/functions.php on line 6274
> 
> Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/domain.tld/wp-content/plugins/newspack-plugin/includes/class-plugin-manager.php:635) in /www/htdocs/domain.tld/wp-admin/includes/misc.php on line 1310
> 
> Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/domain.tld/wp-content/plugins/newspack-plugin/includes/class-plugin-manager.php:635) in /www/htdocs/domain.tld/wp-admin/admin-header.php on line 9
> 
> Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/domain.tld/wp-content/plugins/newspack-plugin/includes/class-plugin-manager.php:635) in /www/htdocs/domain.tld/wp-includes/option.php on line 1050
> 
> Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/domain.tld/wp-content/plugins/newspack-plugin/includes/class-plugin-manager.php:635) in /www/htdocs/domain.tld/wp-includes/option.php on line 1051

**Expected behavior**
Make newspack-plugin work with multisite

**Comment by gamebits** [comment]
Newspack is not intended to work in a multisite environment, but it could fail more gracefully than it does.

![newspack-multisite-on](https://user-images.githubusercontent.com/12199101/128266420-c2f3eb12-b166-44ac-aa24-ac2e26b23d9b.jpg)

**Comment by adekbadek** [comment]
There's no support for multisite now, but we're not ruling it out in future development.

**Comment by jeans** [comment]
We didn't know that, thus we're operating 6 Newspack livesites in 1 multisite setup by now :D 
No Woocommerce or NP campaigns, though.

**Comment by adekbadek** [comment]
Good to know! What I mean is that we don't vouch for a multisite setup, but it might work :)

**Comment by schwabing** [comment]
Hi Adam, has Newspack Multisite ever been discussed again on your end? MS works perfectly fine with NP basic install, you just have to activate the plugin separately for each network site (but not if you activate it network wide). We haven't tried with NP Campaigns, Newsletters, Donations and Subscriptions though. We might give campaigns and newsletters a try soon

**Comment by adekbadek** [comment]
> has Newspack Multisite ever been discussed again on your end?

Not really. 

> We might give campaigns and newsletters a try soon

Newsletters should be fine, but Campaings uses custom DB tables. I'm not sure how that would jive with MS.

**Comment by todearaujo** [comment]
Does Multisite are working?

**Comment by adekbadek** [comment]
As said before, we don't vouch for a multisite setup, but it might work. Use at your own risk. It's not officially supported.

**Comment by jeans** [comment]
Again, we run it NP as Multisite successfully for years and we love it. But: we don’t use the “interactive” functionality, no subscription, newsletters, campaigns. As @adekbadek pointed out, some might work, others won’t. Just give it a try and report back.

**Comment by todearaujo** [comment]
Thanks guys! I'll try.
