### ISSUE TITLE
Newspack WP Admin menu highlighted when it shouldn't be

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#738]
I haven't 100% nailed down how to recreate this, I'm pretty sure it's when the "Click to return to Newspack" banner is showing:

![image](https://user-images.githubusercontent.com/177561/101947884-04702380-3ba6-11eb-9f88-f89acf544397.png)

The hover styles are normal, and clicking on Newspack and back to the Dashboard has fixed it for me before (it it also caused the banner to go away, which is why I think they're related).

These styles seem to be the culprit:

https://github.com/Automattic/newspack-plugin/blob/a4ac3da8c9be6a27ca785f194fb79c4faf6ecded/assets/components/src/with-wizard/style.scss#L9 (specifically the `.toplevel_page_newspack` class).

**Comment by thomasguillot** [comment]
Pretty sure this has been fixed at some point
