### ISSUE TITLE
Tooltips can get super long

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#74]
**Describe the bug**
Originally reported at https://github.com/Automattic/newspack-plugin/pull/73#issuecomment-496272631 by @sonjaleix 

The tooltip should have some sort of graceful handling to account for long tooltips. A max-width may be the best solution.

**To Reproduce**
1. Go to Subscriptions Wizard
2. Hover over the tooltip. Observe it's very wide.

**Screenshots**
<img width="945" alt="Screen Shot 2019-05-28 at 10 19 53 AM" src="https://user-images.githubusercontent.com/7317227/58498257-8d457c80-8132-11e9-9300-6d6755d1b16d.png">

**Expected behavior**
Text should wrap gracefully in the tooltip.

**Comment by thomasguillot** [comment]
This should be fixed in Gutenberg rather than in Newspack since we are using WP's `Tooltip` component. Also, we should probably keep tooltip messaging short and sweet
