### ISSUE TITLE
Text input behavior doesn't match latest designs, bug with 'active' class

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#75]
**Describe the bug**
Originally reported by @justinshreve at https://github.com/Automattic/newspack-plugin/pull/72#issuecomment-496292548

> I've noticed a few behaviors with the components that differ from what I see in the Figma Component file. Let me know if you want me to help tackle these.
> 
> For inputs, the label should still be displayed when active:
> 
> <img width="830" alt="Screen Shot 2019-05-27 at 3 34 32 PM" src="https://user-images.githubusercontent.com/689165/58436765-0e4e3680-8095-11e9-81ca-e3fa65f041a8.png">
> 
> I also noticed that the active class does not get applied if the input is empty. That means the input looks unfocused even though it is. There should be some kind of active but empty state.
> 
> I also noticed that if you tab/keyboard navigate into the inputs, the active class is not appended, even if you begin typing.

**Comment by claudiulodro** [comment]
This is not high priority, as it looks like we'll eventually migrate to `calypso-ui` components.

**Comment by thomasguillot** [comment]
Out of date designs
