### ISSUE TITLE
Campaigns Wizard: Filter Does Not Correctly Represent Inventory

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#759]
**Describe the bug**
When the Campaigns Wizard is first loaded, the filter `SelectControl` correctly corresponds to the available campaigns. When switching between tabs (Overlay/Inline) however, it will always show the options for the previous tab. In addition to being misleading, this creates a situation where a filter option can have no campaigns. When there are no campaigns, the filter select is hidden, thus the user is stuck.

**To Reproduce**
1. Delete all campaigns.
2. Create an overlay campaign in test mode, publish.
3. Create an inline campaign, not test mode, publish.
4. Navigate to Campaigns Wizard. Overlay is the initial tab, observe filter options are correct (All|Test)
5. Click Inline tab. Observe filter options are not correct (All|Test)
6. Click back to Overlay tab. Observe filter options are not correct (All|Active)
7. Change Overlay filter to "Active", observe you are stuck with no way to reset the filter.

**Expected behavior**
Filter options should reflect the current tab.

**Comment by adekbadek** [comment]
No reproducible since changes in #768
