### ISSUE TITLE
Segment List Does Not Refresh After Adding A New Segment

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#773]
**Describe the bug**
After a new segment is created the new item does not appear until page is refreshed.

**To Reproduce**
1. Go to Newspack->Campaigns->Segmentation
2. Add a new Segment, then save.
3. Observe the new segment does not appear in the list.
4. Refresh the page, observe the segment appears.

**Comment by dkoo** [comment]
Adding a note that I see that even after the fix in #774, the segment list does not update if you edit the name of an existing segment.
