### ISSUE TITLE
Option to view and restore deleted Campaigns

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#784]
Currently, if you delete a campaign, it presumably gets sent to trash. But since we're hiding the regular WP posts list UI for campaigns, there's no way to see trashed campaigns to restore them. Should we consider adding a filter to the Campaigns wizard UI to show trashed campaigns, with the option to restore them to draft status?

cc @jeffersonrabb and @thomasguillot

**Comment by thomasguillot** [comment]
Yes
