### ISSUE TITLE
Campaigns Wizard: Trash 

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#786]
The Campaigns wizard needs a way to manage trashed campaigns. Proposed approach is to add "Trash" as an option in the Campaign Groups `SelectControl`. When chosen, display all trashed campaigns. The `Popover` on the right will have only two options — Restore and Delete Permanently. The Trash option will only be displayed if there are campaigns in the trash.

**Comment by thomasguillot** [comment]
Related #784
