### ISSUE TITLE
Alternate Loading Animation

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#788]
The [recent loading animation](https://github.com/Automattic/newspack-plugin/pull/751) makes sense when loading a wizard for the first time, or switching screens. However, it feels wrong when taking a relatively minor action like changing the frequency of a campaign or adding a campaign group. Ideally there could be a subtler loading animation for these actions which allows the wizard to remain visible while the operation is underway.

**Comment by thomasguillot** [comment]
Fixed in https://github.com/Automattic/newspack-plugin/pull/798
