### ISSUE TITLE
Campaign Group Management Tab

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#789]
Now that Campaign Groups are playing an important role, the Campaigns Wizard will need UI for managing them. This should probably be a "Groups" tab, with the following functionality:

- Create group
- Delete group (just the taxonomy term, not the campaigns within)
- Rename group
- Preview group (as segment)
- Activate group
- Deactivate group

**Comment by adekbadek** [comment]
"Groups" are now "Campaigns" (and former "Campaigns" are "Prompts"). The "Campaigns view" has been already implemented.
