### ISSUE TITLE
Campaigns Wizard Popover Triggers Do Not Toggle

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#801]
In the Campaigns Wizard, if the More Options or Campaign Groups `PopOver`s are visible, clicking the icons a second time does not hide them. Instead it animates them in a second time. This appears to be because `onFocusOutside` is firing before `onClick`, so by the time the click event fires the visibility state has already been set to false which causes the `PopOver` to appear again.

**Comment by adekbadek** [comment]
> In the Campaigns Wizard, if the More Options or Campaign Groups PopOvers are visible, clicking the icons a second time does not hide them. 

This is how `@wordpress-components`' `Popover` works. An issue should be opened in https://github.com/WordPress/gutenberg/ instead if this problem is a significant one.

**Comment by adekbadek** [comment]
> When I try to edit or see the current campaigns, some bug is not allowing to list the actual campaigns and just returns to Dashboard.

@estereofonico - this does not seem related to this issue. Would you mind opening a new issue, with a more exhaustive description of the problem?
