### ISSUE TITLE
Wizard: Ads

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#82]
Many publishers have a need to serve advertisements on their site. They may do this through an existing service like Google AdSense or Ad Manager.

Publishers should find it easy to connect ad services they use from within the WordPress dashboard. They should be able to step through a series of steps where they can connect existing accounts, or set up new ones, and begin implementing ads on their site right away.

There are many ads plugins around but a review (pamTN9-fj-p2) found that most were either too cumbersome, or lacked necessary features without needing a paid upgrade.

We are providing configuration and setup through wizards so it will be a more natural UX for there to be an additional wizard for ads.

**Comment by claudiulodro** [comment]
https://github.com/Automattic/newspack-plugin/pull/190 and https://github.com/Automattic/newspack-ads
