### ISSUE TITLE
[Refactor] Handle inFlight status in withWizard HOC

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#825]
Currently, each layout component uses its own `inFlight` state to set the loading state before calling `wizardApiFetch` from the `withWizard` higher-order component. It would be great to offload this loading state to the HOC rather than setting the state in the parent layout component.

**Comment by adekbadek** [comment]
A parent-level is-loading state [has been introduced](https://github.com/Automattic/newspack-plugin/blob/39a247459b4151901799093e8bcd311d4f97abe7/assets/components/src/wizard/index.js#L37) in the new `Wizard` component, which is meant to replace the HOC-based wizard architecture.
