### ISSUE TITLE
[Campaigns] Add New Prompt UI

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#861]
Some ideas I had about the experience of adding new prompts while testing #860. @thomasguillot, feel free to riff on this or close the issue if you think these are unnecessary.

* Maybe this is just my bad memory, but sometimes when I click on "Add New Prompt" I forget a moment later which segment I'm adding to. Could we add some info to this modal that specifies that we're adding a prompt to this specific segment in this specific campaign, maybe under the "Add New Prompt" title?

<img width="398" alt="Screen Shot 2021-02-11 at 2 34 22 PM" src="https://user-images.githubusercontent.com/2230142/107701775-995ece00-6c76-11eb-841f-fdbd60873478.png">

* This modal might also be a good place to add a dropdown to choose a campaign if you're adding from the Active Prompts view. And if you don't select a campaign first, the buttons are disabled—this way we can discourage creating new Unassigned prompts.

* Totally subjective, but in the Add New Prompt modal, the line spacing looks a little too loose to my eyes.

* Also totally subjective, but could the icon buttons and their labels be more visually integrated, perhaps by adopting a wider modal and a horizontally-oriented button? These could collapse to a single column for smaller viewports. We might also want to consider adding some short descriptions of what each placement is to help new users. e.g. something like this, but better-looking 😄 

<img width="613" alt="Screen Shot 2021-02-11 at 3 20 41 PM" src="https://user-images.githubusercontent.com/2230142/107705911-bdbda900-6c7c-11eb-8e72-27d674d8353e.png">

**Comment by dkoo** [comment]
A follow-up. I had a convo with @iamstevebeatty about Campaigns today, and he has an alternative selection which I will present here for further discussion: rather than showing a single modal that only lets you choose the prompt's placement, what if the modal was more of a guided experience that makes you choose the most important settings for a new prompt? This would include:

1. "Where do you want the prompt to appear?" ➜ Placement dropdown, defaulting to "inline"
2. "How often do you want the prompt to appear?" ➜ Frequency dropdown, defaulting to "until dismissed" for inline/"once a day" for overlays
3. "Should the prompt be shown with specific categories?" ➜ Category filtering autocomplete, defaulting to none

Then, once the user clicks "OK", they get forwarded to the editor page as usual. BUT, if the options selected would result in a conflict with an existing active prompt, we could show a warning at this point before letting the user proceed, e.g. "This prompt will conflict with the following active prompt(s): [show a list]"

Not sure if this would complicate things too much, but I thought it was worth adding to the mix.

**Comment by dkoo** [comment]
Noting that we need to figure out a way to add the seventh "Manual Only" option to the grid: https://github.com/Automattic/newspack-plugin/pull/1013#issuecomment-874012747

**Comment by thomasguillot** [comment]
@dkoo after exploring a few solutions to display the  "Manual Only" option, I think we shouldn't display it.

It breaks the grid. We could switch to something like 3 / 2 / 2 but it is really worth it?

![Screenshot 2021-07-09 at 12 16 54](https://user-images.githubusercontent.com/177929/125070480-ed4bd280-e0af-11eb-9233-ca0ff048c0bd.png)

"Manual Only" feels like a legacy option more than anything and users should be using "Custom Placement" instead. [From our support site](https://newspack.pub/support/campaigns/custom-placements/):

> Note: The Custom Placements system replaces the “Manual Placement” frequency and manual placement of prompts via shortcodes. Prompts with the “manual placement” frequency will be automatically reassigned to a custom placement instead, with the default “Until Dismissed” frequency. Prompts placed manually via shortcode will continue to work for legacy purposes, but we recommend replacing these with custom placement blocks to ensure that they continue being displayed in the future.

**Comment by dkoo** [comment]
> @dkoo after exploring a few solutions to display the "Manual Only" option, I think we shouldn't display it.

I'm okay with this. I agree that in most cases editors should be using Custom Placement instead of Manual Only, and that the latter is more of an advanced/very specific use case.

**Comment by thomasguillot** [comment]
> A follow-up. I had a convo with @iamstevebeatty about Campaigns today, and he has an alternative suggestion which I will present here for further discussion: rather than showing a single modal that only lets you choose the prompt's placement, what if the modal was more of a guided experience that makes you choose the most important settings for a new prompt? This would include:
> 
> 1. "Where do you want the prompt to appear?" ➜ Placement dropdown, defaulting to "inline"
> 2. "How often do you want the prompt to appear?" ➜ Frequency dropdown, defaulting to "until dismissed" for inline/"once a day" for overlays
> 3. "Should the prompt be shown with specific categories?" ➜ Category filtering autocomplete, defaulting to none
> 
> Then, once the user clicks "OK", they get forwarded to the editor page as usual. BUT, if the options selected would result in a conflict with an existing active prompt, we could show a warning at this point before letting the user proceed, e.g. "This prompt will conflict with the following active prompt(s): [show a list]"
> 
> Not sure if this would complicate things too much, but I thought it was worth adding to the mix.

I think it would make things quite complicated and I like the simplicity of the current modal
