### ISSUE TITLE
Prompt deletion & trashes, all prompts views

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#869]
Slightly related issues:

1. **Prompt deletion**. As is: prompt deletion in the Campaigns Wizard offers no confirmation and omits trash. Should be: deletion should allow the user to confirm, and the deleted prompt should be moved to trash instead of deleted permanently.
2. **Trash view**. After the above is done, a "Trash" filter should be added to the view selection (same as https://github.com/Automattic/newspack-plugin/issues/786, not closing yet cause that might be too much for one PR).
3. **All prompts view**. An "All Prompts" view should be added tot the view selector.

**Comment by jeffersonrabb** [comment]
I've also heard interest in an "Inactive Prompts" view - essentially every prompt that is not visible in "Active Prompts."
