### ISSUE TITLE
Ads Wizard throws fatal error on load if Newspack Ads isn't installed + active

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#880]
**Describe the bug**
When going to the Advertising wizard, if the Newspack Ads plugin isn't installed and active, the wizard throws a fatal error and kicks the user back to the main dashboard.

**To Reproduce**
1. Deactivate Newspack Ads
2. Go to Ads wizard. It should throw an unrecoverable `data.ad_units.reduce is not a function` error.

**Screenshots**

<img width="1654" alt="Screen Shot 2021-02-23 at 4 18 52 PM" src="https://user-images.githubusercontent.com/7317227/108926375-26990f80-75f3-11eb-9f5c-f120fc3d9ca1.png">

**Expected behavior**
I expect it to bring up that screen for automatically installing/activating Newspack Ads if the user tries to go to the wizard and the required plugin isn't active.

**Comment by adekbadek** [comment]
Similar to the [issue with Reader Revenue](https://github.com/Automattic/newspack-plugin/pull/1042#issuecomment-882545950) - this can happen if `WP_NEWSPACK_DEBUG` is on. Then, plugin checks are omitted.
