### ISSUE TITLE
Add server-side validation of segments list before executing a re-sort

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#882]
**Is your feature request related to a problem? Please describe.**
#881 illustrates that the new segment sorting UI has a weakness: because the sorting comes from the client-side render, it's possible to mess up your segments list pretty badly. Even after #881 lands (which fixes a bug where you can duplicate segments if you sort while a sort op is already in progress), some problems persist. For example:

1. Go to Newspack > Campaigns > Segments
2. Create a new segment and save.
3. Open a second tab in the same browser and go to Newspack > Campaigns > Segments again. Observe that the segments list is the same across both tabs.
4. In tab 1, delete the new segment.
5. In tab 2, without refreshing, drag and drop the new segment to another spot in the list.
6. Refresh tabs 1 and 2. Observe that the new segment has come back from the dead despite having been deleted in step 4.

**Describe the solution you'd like**
As part of the `segmentation-sort` endpoint handler, we should validate the updated list of segments being passed against the existing list of segments from the options table, so that:

- The number of items is the same in both lists
- Each item in the updated list has a unique ID (no duplicates)
- Each item in the updated list has an ID that exists in the list from the options table

If any of the above conditions fail, we should abort the sorting operation and return a WP Error.

**Describe alternatives you've considered**
Maybe we should also consider fetching an updated segments list every time you start a sort op, and abort if the initial order doesn't match. This would help prevent a similar problem if you sort the list a certain way in one tab while another tab is open, then sort in the other tab (the order persisted to the database will match tab 2).

Open to other suggestions! 

**Additional context**
This should hopefully guard against most potential screw-ups due to bad info coming from the client-side UI being persisted in the database.

**Comment by adekbadek** [comment]
Since the endpoint is handling sorting only, the frontend could send just the ordered list of IDs, based on which the backend would sort. E.g. with payload `['a', 'b', 'c']` sent, and the segments of ids `'a'` and `'b'` only present, the result would be segments sorted in order `['a', 'b']`. For more robustness, a single check could be to make an array diff of existing vs. incoming ids - if there's any difference, return error.
