### ISSUE TITLE
Implement new checklist style

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#89]
Let's align the current checklist component (#31) with the Jetpack checklist based on Muriel design principles. 

Here are first mockups: 

Checklist first step:
<img width="790" alt="Screenshot 2019-06-05 16 36 22" src="https://user-images.githubusercontent.com/4823744/58995145-3e41bc00-87b0-11e9-9224-6744efe49fe2.png">

Checklist containing some completed items
<img width="733" alt="Screenshot 2019-06-05 16 37 06" src="https://user-images.githubusercontent.com/4823744/58995148-426dd980-87b0-11e9-8773-bce22a8385dc.png">

More details about UX and expected behavior can be found [here](https://murielp2.wordpress.com/2019/05/28/muriel-meets-the-checklist/).

**Comment by jeffersonrabb** [comment]
After discussing this a bit with @sonjaleix I wanted to raise a few possible issues with the new checklist direction for the Newspack use case. The big overall question is whether our checklists should require linear completion.

- Visibility controls for each row suggest that list items do not need to be addressed in order. These make it easy to open a future list item and act on it. In the Newspack use of these lists, does non-linear list completion make sense?

- Moving completed items to a separate group at the bottom creates an implementation complexity. Doing this would require reordering the child `Tasks` with completed ones at the bottom and incomplete ones at the top. This means the order of items in the rendered component may differ from the order in the JSX, which seems peculiar. 

- Separate from the implementation difficulty, it feels odd to move completed items to the bottom of a list meant to be completed in linear order. Like the visibility controls, this change seems to suggest that the list can be completed in any order the user wishes, which may not be a fit for the Newspack use cases.

- Does the "Estimated Time" clue have meaning for Newspack? Newspack assumes the customer is highly committed to their site, so trying to convince them that the setup will take minimal time may be unnecessary. Also, in some of our wizards the checklist will be used as a way to engage in post-setup maintenance, in which case the idea of estimated time doesn't have the same meaning.

- Do the icons bring value in the Newspack use case? The add nice visual flair, but I wonder if we'll end up in a situation where the available icons don't align cleanly with the nature of tasks and we overuse general ones or are forced to devote design resources to creating new icons.

**Comment by philipjohn** [comment]
> does non-linear list completion make sense?

After the initial set up, yes.

We originally talked about wizards being both the setup screen and the configuration screen. Essentially, a settings screen but presented as a wizard so it's clear how to get going but also easy to go back in and modify anything at a later date *after first set up*. I still think that's the route we should take with these.

To that end, I think we want linear progression on first set up, but the ability to go back into specific steps at a later date to tweak settings. Having the steps presented linearly also helps to show how steps may depend on each other.

> Does the "Estimated Time" clue have meaning for Newspack?

To me it's superfluous but it's also not harmful. Perhaps some people will be put off by what may look like a big task list, and the time estimates could help alleviate concern they're going to be configuring for ages. You know that feeling when someone sends you a survey and it says there are 30 steps? ... yeah, that.

**Comment by sonjaleix** [comment]
We can probably close this one since we concluded that the checklists UI isn't working us.

**Comment by jeffersonrabb** [comment]
Agreed. Closing...
