### ISSUE TITLE
Starter Content: Removing it removes same-named categories

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#899]
Note: This may not be a bug with how debug mode/the starter content is intended to work going forward. I ran into this setting up a staging site; I was running the wizard to make sure all of the appropriate plugins were installed and configured; I'm filing it as an issue compared to how the starter content used to work, as an optional step rather than a required one. 

**Describe the bug**
If you run the Newspack wizard with debug mode enabled, it will automatically install starter content. Clicking 'Remove Starter Content' works, but if you also happen to have any categories with the same names as the starter content -- like Features or Opinion -- they will also be removed. 

**To Reproduce**
1. Start on a test site with some content with a few of the starter content categories, like 'Opinion'. 
2. Switch the plugin to debug mode by adding `define( "WP_NEWSPACK_DEBUG", true );` to the `wp-config.php` file.
3. Run the Newspack Wizard.
4. At the end, click 'Remove Starter Content`.
5. Check your categories; note that the ones that overlap with the starter content are missing. 

**Screenshots**
Test site before running the setup wizard, with four posts under Opinion:

![image](https://user-images.githubusercontent.com/177561/110046247-8af95480-7d00-11eb-951a-c440cc40d4c5.png)

Categories after running setup wizard:

![image](https://user-images.githubusercontent.com/177561/110046388-c5fb8800-7d00-11eb-9037-af3373bd49a1.png)

Categories after clicking "Remove Starter Content" -- my original five posts are there, but now they're all filed under Uncategorized, and the original Opinion category is gone:

![image](https://user-images.githubusercontent.com/177561/110046450-e3305680-7d00-11eb-8695-e201a85669fb.png)

**Expected behavior**
I'm not sure the best outcome here - of course, the starter content shouldn't add duplicate categories, either, so it makes sense that it didn't create a second Opinion category. 

Ideally the starter content wouldn't be installed unless triggered, or at least there would be a prompt in cases where the site isn't empty. 

The starter categories could also be replaced with something that's unlikely to actually be a category on a real site -- like Lorem Ipsum. The downside is it would make the content look "less real", but there wouldn't be the need to try to keep track of what categories already existed.

**Comment by jeffersonrabb** [comment]
One way to address this would be to set term meta for the starter categories identifying that they were created by the wizard, then using this to identify and delete them. Also we could change the names to something indicating they are temporary.

**Comment by thomasguillot** [comment]
Do we actually need multiple categories for the starter content anyway? Can't we just create one something like "Newspack Demo Content" and add all the demo posts to it?
