### ISSUE TITLE
Setup Wizard: Overwrites existing customizations

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#903]
Note: this is a similar issue to #899, in that I'm not sure how the setup wizard is imagined to be used, and it's also related to the starter content. I could be misunderstanding it, and where it fits with our process of setting up sites for publishers. 

**Describe the bug**
If you run the setup wizard after customizing the site in any way, you'll overwrite some of your customization work -- specifically, the logo, the header settings, and your selected homepage. 

Right now I've been skipping the setup wizard due #899 to when Newspackifying a site, but there has now been a couple cases where it's run later, and work is undone. 

**To Reproduce**
1. Install the Newspack plugin and theme on a fresh site (edited to add: this recreates more of our usual staging site situation, not a brand-new site situation -- the themes are already in place).
2. Install and activate the Newspack Blocks plugin.
3. Go about customizing your site: add a logo, menu, and set up a homepage. Keep the header with the default settings (default height, default background).

![Screen Shot 2021-03-12 at 8 04 16 AM](https://user-images.githubusercontent.com/177561/110966775-7faeb600-830a-11eb-9e4e-9cd83fba9767.png)

4. Navigate to WP Admin > Newspack and run the Setup Wizard.
5. View the site again: 

![Screen Shot 2021-03-12 at 8 07 40 AM](https://user-images.githubusercontent.com/177561/110966845-92c18600-830a-11eb-95ed-d871241289f7.png)

Some settings (colours, fonts, menus, Custom CSS) are kept, and your homepage itself isn't entirely overwritten, a new page is created and replaces it under Customizer > Homepage Settings. Both your logo and header settings are overwritten, though.

**Expected behavior**
I would expect if a logo or front page is set, it wouldn't be overwritten.

For the header settings, it's a bit tougher -- in my case, they were using the default settings (which is a totally viable setup), so there's nothing really to check for. 

Again, this might be a case where we need some kind of prompt before adding the starter content to the site.

**Comment by adekbadek** [comment]
#905 solves the logo overwrite, the other expected behaviours should be covered by the optionality of starter content creation.
