### ISSUE TITLE
Option for installing demo content

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#904]
The new UI in #851 removed the option to not install demo content (now, demo content is always installed). We should add the option back because not all sites will need or want the demo content. This will let us avoid #899 for new sites until we have a proper fix for that issue.

Mockup courtesy @thomasguillot:

![Screenshot 2021-03-12 at 17 06 38](https://user-images.githubusercontent.com/2230142/110976559-45e7aa80-831e-11eb-986b-06a6e1d4b8f4.png)

**Comment by avcascade** [comment]
Looks good!
