### ISSUE TITLE
Campaigns Wizard UI: tag filtering

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#926]
**Describe the issue**

Now that [tag filtering has been fixed in the Campaigns plugin](https://github.com/Automattic/newspack-popups/pull/506), that functionality is currently a bit hidden with the only indication that you can filter by tag being the Tags panel in the editor page for prompt. We should add UI for this in the Campaigns wizard alongside category filtering. However, the submenus are getting a bit cluttered, so @thomasguillot [suggests a third submenu](https://github.com/Automattic/newspack-popups/pull/506#issuecomment-811757278) specifically for filtering options to contain both category and tag filter fields.

**Comment by adekbadek** [comment]
@thomasguillot with the addition of GA insights (#1057), the third submenu idea might have to be reevaluated, WDYT?

**Comment by thomasguillot** [comment]
I agree. It's getting extremely cluttered now! I wonder if we could move the content of this popover to a `Modal` instead?

**Comment by adekbadek** [comment]
Makes sense!

**Comment by dkoo** [comment]
I like the idea of a modal too.
