### ISSUE TITLE
Onboarding Loop

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-plugin#933]
**Describe the bug**
During Onboarding, if "Install Demo Content" is unchecked, some sort of a loop occurs. At the end of onboarding, when "Finish" is clicked on design step, the wizard starts over. After going through the whole sequence of screens a second time, onboarding concludes and the Newspack dashboard loads properly. Curiously I wasn't able to replicate this reliably on Jurassic Ninja site, although I've seen it several times on Newspack Atomic sites.

**Comment by adekbadek** [comment]
Might be a caching issue. I've verified that on a fresh atomic site - the option that [governs the dashboard-to-settings redirection](https://github.com/Automattic/newspack-plugin/blob/896c1bce095b3f0ac3c91067426e4b8f9e8899b4/includes/wizards/class-setup-wizard.php#L46-L49) is set, but still the redirection occurs.

**Comment by thomasguillot** [comment]
Cannot replicate
