### ISSUE TITLE
Integrate newspack-scheduled-post-checker plugin

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-plugin#939]
**Is your feature request related to a problem? Please describe.**
@tmmbecker mentions that she's been installing the [newspack-scheduled-post-checker plugin](https://github.com/Automattic/newspack-scheduled-post-checker) on a lot of Newspack sites. Since it's such a small and useful tool, we should consider integrating it into this main Newspack plugin and deprecating the separate plugin repo.

Alternatively, we could keep the plugin separate but whitelist it as a managed plugin and let it be installed automatically as part of the Newspack product suite. This would require that we set up the separate repo with the requisite CI workflows.

**Describe the solution you'd like**
I think the easiest solution is to bring over the code from the other plugin and integrate it here. Since both plugins are licensed under GPL2, there'd be no loss to the open source community. 

**Describe alternatives you've considered**
The alternative, if we'd like to keep the plugin separate, is to bring it up-to-date with our deployment and release management workflows, then whitelist it as part of the larger Newspack suite. This might be a more attractive option for larger or more complex plugins (or ones that not every Newspack site might need), but newspack-scheduled-post-checker is very small, very low-risk, and extremely useful for any site that publishes a lot of content frequently.

cc @claudiulodro @adekbadek

**Comment by adekbadek** [comment]
I'm for integrating it into the Newspack plugin.
