### ISSUE TITLE
Back button to checklist within WP Admin

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#95]
We're sending users from our checklists to complete various actions/tasks in other places around the WordPress Admin (e.g. The Editor, a plugin's dashboard, etc.). We'd like to establish a UI pattern to help guide users back to the checklist upon completion of the task.

For this I was looking at what UI patterns exist that we could potentially reuse. .com has designed a UI pattern of a banner that appears after a specific action has been completed (see [screenshot here](https://www.dropbox.com/s/tbq7kkhgyk3obee/Screenshot%202019-06-10%2011.19.33.png?dl=0)). 

I believe this has been built and we should look at reuse it.

**Comment by claudiulodro** [comment]
#105
