### ISSUE TITLE
Installing/Activating a plugin in a separate tab breaks Plugin Installer flow.

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-plugin#97]
**Describe the bug**
Originally reported at https://github.com/Automattic/newspack-plugin/pull/86#issuecomment-500390719.

Installing/Activating a required plugin in a separate tab will cause errors to be shown in the Plugin Installer and prevent proceeding to the next screen.

**To Reproduce**
1. Deactivate AMP. Go to the Components Demo. Observe that 'Use' is next to the AMP plugin on the Plugin Installer component.
2. In a separate tab, activate the AMP plugin using the regular WP plugins screen.
3. In the original tab, click 'Use' to try and activate the AMP plugin. Observe a "The plugin is already active" error displays and the Plugin Installer fails.

**Screenshots**
<img width="483" alt="Screen Shot 2019-06-11 at 8 20 51 AM" src="https://user-images.githubusercontent.com/7317227/59285344-b2ea7f80-8c22-11e9-9222-0bc1bafbb922.png">

**Expected behavior**
I think either the `PluginInstaller` component should ignore `newspack_plugin_already_active` and `newspack_plugin_already_installed` errors, or we shouldn't throw those errors in the `Plugin_Manager` (just return success if someone tries to re-activate an active plugin).

**Comment by adekbadek** [comment]
Not reproducible anymore.
