### ISSUE TITLE
ActionCard: Create popover reusable component

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-plugin#977]
We use this type of ActionCard in various places and it'd make sense to create a new component for it so it's easier to reuse throughout the plugin.

cc @dkoo 

See https://github.com/Automattic/newspack-plugin/pull/971#discussion_r636281705 and https://github.com/Automattic/newspack-plugin/pull/971#pullrequestreview-666007572

**Comment by adekbadek** [comment]
Closing as stale. Refactoring this is a nice idea, but not a huge priority.
