### ISSUE TITLE
Campaigns: Improve automatic placements

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-plugin#989]
Wisconsin Watch reported that their Recent Stories campaign often breaks the story text in odd places:

![Screen Shot 2021-06-02 at 3 32 27 PM](https://user-images.githubusercontent.com/22805865/120657926-f7e0cf80-c452-11eb-99a2-278915598e45.png)

[Post link](https://wisconsinwatch.org/2021/06/la-crosse-teacher-julie-welch-reflects-on-freedoms-brought-by-vaccination/)

![Screen Shot 2021-06-02 at 3 34 21 PM](https://user-images.githubusercontent.com/22805865/120657928-f8796600-c452-11eb-9472-d455101cb90b.png)

[Post link](https://wisconsinwatch.org/2021/05/a-milwaukee-man-explains-how-his-college-debt-spiraled-out-of-control-and-how-to-avoid-a-similar-fate/)

![Screen Shot 2021-06-02 at 3 36 58 PM](https://user-images.githubusercontent.com/22805865/120657929-f911fc80-c452-11eb-8a66-ad77c86cd155.png)

[Post link](https://wisconsinwatch.org/2021/04/wisconsin-multigenerational-homes-high-covid-19-risk/)

-----

The [inline prompt](https://wisconsinwatch.org/wp-admin/post.php?post=1262604&action=edit#) is a homepage posts block that is set to display just the titles at 35%. It appears that we're not gracefully accounting for inline images or sub-headings. 

* Could we amend the content detection to better account for the right- and left- adjusted images? Can we set the logic to avoid adding a prompt after a header block? 
* Alternatively, can we add a means to manually override an inline prompt per-post?

**Comment by adekbadek** [comment]
_Moved to https://github.com/Automattic/newspack-popups/issues/555_
