### ISSUE TITLE
Campaigns Analytics: insights in the list view

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#993]
## As is:

To get a per-prompt GA data, user has to drill down in the Campaigns Analytics view chart.

## To be:

Display analytics data in the list view, per-prompt:

![image](https://user-images.githubusercontent.com/7383192/121190560-79799880-c86b-11eb-9cad-5960218347f9.png)

cc @thomasguillot

**Comment by thomasguillot** [comment]
Another idea
![Screenshot 2021-06-08 at 16 47 53](https://user-images.githubusercontent.com/177929/125491471-a9e0db74-7af5-4a32-8551-9eec88c4beaa.png)
